# Autolabel the different apps
activemembers:
  - website/activemembers/**
announcements:
  - website/announcements/**
documents:
  - website/documents/**
education:
  - website/education/**
events:
  - website/events/**
mailinglists:
  - website/mailinglists/**
members:
  - website/members/**
merchandise:
  - website/merchandise/**
newsletter:
  - website/newsletters/**
partners:
  - website/partners/**
payments:
  - website/payments/**
photos:
  - website/photos/**
pizzas:
  - website/pizzas/**
promotion:
  - website/promotion/**
push-notifications:
  - website/pushnotifications/**
registrations:
  - website/registrations/**
sales:
  - website/sales/**
singlepages:
  - website/singlepages/**
thabloid:
  - website/thabloid/**
