version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    groups:
      patch-updates:
        update-types:
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # These are also set in .pre-commit-config.yaml
      # They shouldn't go out of sync, so we only change them manually.
      - dependency-name: "black"
      - dependency-name: "isort"
      - dependency-name: "ruff"
    labels:
      - "dependency-update"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency-update"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency-update"
