# Generated by Django 4.2 on 2023-05-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facedetection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facedetectionphoto",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("done", "Done"),
                    ("rejected", "Rejected"),
                ],
                default="processing",
                help_text="Status of the encoding extraction process.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="referenceface",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("done", "Done"),
                    ("rejected", "Rejected"),
                ],
                default="processing",
                help_text="Status of the encoding extraction process.",
                max_length=16,
            ),
        ),
    ]
