# Generated by Django 4.2.1 on 2023-05-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facedetection", "0002_alter_facedetectionphoto_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facedetectionphoto",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The time at which the source was submitted to the Lambda for processing.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="referenceface",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The time at which the source was submitted to the Lambda for processing.",
                null=True,
            ),
        ),
    ]
