# Generated by Django 4.2.1 on 2023-05-05 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("facedetection", "0003_facedetectionphoto_submitted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="referenceface",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
