# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0004_auto_20160727_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='public/committeephotos/', verbose_name='Image'),
        ),
    ]
