# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0005_auto_20160813_2203'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='committeemembership',
            managers=[
            ],
        ),
    ]
