# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0007_mentors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mentors',
            new_name='Mentorship',
        ),
    ]
