# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0008_auto_20160906_1015'),
        ('committees', '0006_auto_20160824_2201'),
    ]

    operations = [
    ]
