# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 17:31
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0008_auto_20160906_1015'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='committee',
            managers=[
                ('unfiltered_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
