# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 17:34
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0009_merge_20160907_1918'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='committee',
            managers=[
                ('active_committees', django.db.models.manager.Manager()),
            ],
        ),
    ]
