# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 12:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
from thabloid.models.thabloid import thabloid_filename


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thabloid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990)])),
                ('issue', models.IntegerField()),
                ('file', models.FileField(upload_to=thabloid_filename, validators=[])),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='thabloid',
            unique_together=set([('year', 'issue')]),
        ),
    ]
