# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thabloid', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thabloid',
            options={'ordering': ('-year', '-issue')},
        ),
    ]
