# Generated by Django 2.0.1 on 2018-03-07 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thabloid', '0002_auto_20170129_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thabloid',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1990)], verbose_name='academic year'),
        ),
    ]
