# Generated by Django 2.1.7 on 2019-03-27 18:48

import django.core.validators
from django.db import migrations, models
from thabloid.models.thabloid import thabloid_filename


class Migration(migrations.Migration):

    dependencies = [
        ('thabloid', '0003_auto_20180307_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thabloid',
            name='file',
            field=models.FileField(upload_to=thabloid_filename, validators=[django.core.validators.FileExtensionValidator(['.txt', '.pdf', '.jpg', '.jpeg', '.png'])]),
        ),
    ]
