# Generated by Django 2.2.1 on 2019-05-16 13:36

import django.core.validators
from django.db import migrations, models
import thabloid.models


class Migration(migrations.Migration):

    dependencies = [
        ('thabloid', '0004_auto_20190327_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thabloid',
            name='file',
            field=models.FileField(upload_to=thabloid.models.thabloid_filename, validators=[django.core.validators.FileExtensionValidator(['txt', 'pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
