# Generated by Django 4.2.4 on 2023-09-09 13:40

from django.db import migrations
import thabloid.models.thabloid
import thumbnails.fields


class Migration(migrations.Migration):
    dependencies = [
        ("thabloid", "0008_thabloid_user_blacklistedthabloiduser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thabloid",
            name="cover",
            field=thumbnails.fields.ImageField(
                upload_to=thabloid.models.thabloid.thabloid_cover_filename
            ),
        ),
    ]
