name: concrexit

services:
  concrexit:
    image: ghcr.io/svthalia/concrexit:${TAG}
    env_file:
      - env.public
      - env.secret
    volumes:
      - concrexit-media:/volumes/media:rw
      - concrexit-static:/volumes/static:rw
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: ghcr.io/svthalia/concrexit-nginx:${TAG}
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - env.public
    volumes:
      - letsencrypt:/etc/letsencrypt:rw
      - concrexit-media:/volumes/media:ro
      - concrexit-static:/volumes/static:ro
    restart: always
    depends_on:
      concrexit:
        condition: service_started

  postgres:
    image: postgres:15.3-alpine
    env_file:
      - env.public
    volumes:
      - /volumes/postgres/data:/var/lib/postgresql/data:rw
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "--username", "concrexit"]
      interval: 2s
      timeout: 2s
      retries: 30

volumes:
  concrexit-media:
  concrexit-static:
  letsencrypt:
