name: concrexit-${STAGE}

services:
  concrexit:
    build:
      context: ..
      dockerfile: infra/concrexit/Dockerfile
    env_file:
      - .env.public
      - .env.public.${STAGE}
      - .env.secret.${STAGE}
    volumes:
      - concrexit-static:/static:rw
      - concrexit-media:/media:rw
    # TODO: cronjobs and package registry instead of build
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    build:
      context: nginx
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env.public
      - .env.public.${STAGE}
    volumes:
      - concrexit-static:/vol/static:ro
      - concrexit-media:/vol/media:ro
      - letsencrypt:/etc/letsencrypt:rw
    restart: always
    depends_on:
      concrexit:
        condition: service_started

  postgres:
    image: postgres:11.19-alpine
    env_file:
      - .env.public
      - .env.public.${STAGE}
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "--username", "concrexit"]
      interval: 3s
      timeout: 1s
      retries: 20

volumes:
  postgres-data:
  concrexit-static:
  concrexit-media:
  letsencrypt:
