# Generated by Django 2.0.1 on 2018-02-03 13:59

import uuid
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0005_move_payment_model_to_app'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('type', models.CharField(blank=True, choices=[('cash_payment', 'Cash payment'), ('card_payment', 'Card payment')], max_length=20, null=True, verbose_name='type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('processed', models.BooleanField(default=False, verbose_name='processed')),
                ('processing_date', models.DateTimeField(blank=True, null=True, verbose_name='processing date')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'permissions': (('process_payments', 'Process payments'),),
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
