# Generated by Django 2.1.5 on 2019-02-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20181127_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('no_payment', 'No payment'), ('cash_payment', 'Cash payment'), ('card_payment', 'Card payment'), ('wire_payment', 'Wire payment')], default='no_payment', max_length=20, verbose_name='type'),
        ),
    ]
