# Generated by Django 2.2 on 2019-04-27 19:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localflavor.generic.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_benefactor_model_value'),
        ('payments', '0003_auto_20190204_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('initials', models.CharField(max_length=20, verbose_name='initials')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('iban', localflavor.generic.models.IBANField(include_countries=('AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GI', 'GR', 'HR', 'HU', 'IE', 'IS', 'IT', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK', 'SM'), max_length=34, use_nordea_extensions=False, verbose_name='IBAN')),
                ('bic', localflavor.generic.models.BICField(blank=True, help_text='This field is optional for Dutch bank accounts.', max_length=11, null=True, verbose_name='BIC')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='valid from')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='valid until')),
                ('signature', models.TextField(blank=True, null=True, verbose_name='signature')),
                ('mandate_no', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='mandate number')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='members.Member', verbose_name='owner')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
