# Generated by Django 3.0.2 on 2020-02-19 21:00

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20191030_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('no_payment', 'No payment'), (payments.models.Payment.Type['CASH'], 'Cash payment'), (payments.models.Payment.Type['CARD'], 'Card payment'), (payments.models.Payment.Type['TPAY'], 'Thalia Pay payment'), (payments.models.Payment.Type['WIRE'], 'Wire payment')], default='no_payment', max_length=20, verbose_name='type'),
        ),
    ]
