# Generated by Django 2.2.9 on 2020-01-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20191109_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'permissions': (('process_batches', 'Process batch'),), 'verbose_name': 'batch', 'verbose_name_plural': 'batches'},
        ),
    ]
