# Generated by Django 2.2.1 on 2019-11-09 17:36

from django.db import migrations, models
import django.db.models.deletion
import payments.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20191030_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('processed', models.BooleanField(default=False, verbose_name='processing status')),
                ('processing_date', models.DateTimeField(blank=True, null=True, verbose_name='processing date')),
                ('description', models.TextField(default=payments.models._default_batch_description, verbose_name='description of batch')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_set', to='payments.Batch'),
        ),
    ]
