# Generated by Django 3.1.1 on 2020-09-18 17:21

from django.db import migrations, models
import django.db.models.deletion
import payments.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20200905_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('processed', models.BooleanField(default=False, verbose_name='processing status')),
                ('processing_date', models.DateTimeField(blank=True, null=True, verbose_name='processing date')),
                ('description', models.TextField(default=payments.models._default_batch_description, verbose_name='description')),
            ],
            options={
                'verbose_name': 'batch',
                'verbose_name_plural': 'batches',
                'permissions': (('process_batches', 'Process batch'),),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_set', to='payments.batch'),
        ),
    ]
