# Generated by Django 3.1.1 on 2020-09-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20200918_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Users can revoke the mandate at any time, as long as they do not have any Thalia Pay payments that have not been processed. If you revoke a mandate, make sure to check that all unprocessed Thalia Pay payments are paid in an alternative manner.', null=True, verbose_name='valid until'),
        ),
    ]
