# Generated by Django 3.1.1 on 2020-09-29 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20200921_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='withdrawal_date',
            field=models.DateField(default=datetime.date(2020, 10, 13), verbose_name='withdrawal date'),
        ),
    ]
