# Generated by Django 3.1.1 on 2020-09-30 18:55

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20200921_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='withdrawal_date',
            field=models.DateField(default=payments.models._default_withdrawal_date, verbose_name='withdrawal date'),
        ),
    ]
