# Generated by Django 3.1.1 on 2020-10-12 20:17

from django.db import migrations, models
import django.db.models.deletion
import members.models.member


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_remove_profile_language'),
        ('payments', '0012_batch_withdrawal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentUser',
            fields=[
            ],
            options={
                'verbose_name': 'payment user',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('members.member',),
            managers=[
                ('objects', members.models.member.MemberManager()),
                ('current_members', members.models.member.CurrentMemberManager()),
                ('active_members', members.models.member.ActiveMemberManager()),
            ],
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='payments.paymentuser', verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_payment_set', to='payments.paymentuser', verbose_name='paid by'),
        ),
    ]
