# Generated by Django 3.1.1 on 2020-10-16 19:22

from django.db import migrations, models
import django.db.models.deletion
import payments.models

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_auto_20201012_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='batch',
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.BooleanField(default=False,
                                                  verbose_name='processing status')),
                ('processing_date', models.DateTimeField(blank=True, null=True,
                                                         verbose_name='processing date')),
                ('description', models.TextField(
                    default=payments.models._default_batch_description,
                    verbose_name='description')),
                ('withdrawal_date', models.DateField(default=payments.models._default_withdrawal_date, verbose_name='withdrawal date')),
            ],
            options={
                'verbose_name': 'batch',
                'verbose_name_plural': 'batches',
                'permissions': (('process_batches', 'Process batch'),),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    related_name='payments_set',
                                    to='payments.batch'),
        ),
    ]
