# Generated by Django 3.1.1 on 2020-10-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_auto_20201016_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentuser',
            options={'permissions': (('tpay_allowed', 'Is allowed to use Thalia Pay'),), 'verbose_name': 'payment user'},
        ),
    ]
