# Generated by Django 3.1.6 on 2021-02-24 13:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('payments', '0015_auto_20201017_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentUserCache',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payment_user_cache', serialize=False, to='auth.user')),
                ('allowed', models.BooleanField(null=True)),
                ('enabled', models.BooleanField(null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='amount')),
            ],
        ),
    ]
