# Generated by Django 3.1.3 on 2020-12-14 19:22

from django.db import migrations, models
import django.db.models.deletion
from payments.models import BankAccount

def forwards_func(apps, schema_editor):
    OldBankAccount = apps.get_model("payments", "BankAccount")
    OldPaymentUser = apps.get_model("payments", "PaymentUser")
    db_alias = schema_editor.connection.alias
    # for account in BankAccount.objects.all():
    for account in OldBankAccount.objects.using(db_alias).all():
        user_pk = account.owner.pk
        account.owner = user_pk
        account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_remove_profile_language'),
        ('payments', '0015_auto_20201017_1354'),
    ]
    operations = [
        migrations.DeleteModel(
            name='PaymentUser',
        ),
        migrations.CreateModel(
            name='PaymentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_tpay_enabled', models.BooleanField(default=False, verbose_name='Thalia Pay enabled')),
                ('_tpay_allowed', models.BooleanField(default=False, verbose_name='Allowed to use Thalia Pay')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'verbose_name': 'payment user',
            },
        ),
        migrations.AlterField(
            model_name='Payment',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_payment_set', to='payments.paymentuser', verbose_name='paid by'),
        ),
        migrations.AlterField(
            model_name='BankAccount',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='payments.paymentuser', verbose_name='owner'),
        ),
        migrations.RunPython(code=forwards_func),
    ]

