# Generated by Django 3.2 on 2021-05-31 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_auto_20201017_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedPaymentUser',
            fields=[
                ('payment_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='payments.paymentuser')),
            ],
        ),
        migrations.AlterModelOptions(
            name='paymentuser',
            options={'verbose_name': 'payment user'},
        ),
    ]
