# Generated by Django 3.1.7 on 2021-03-23 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_remove_profile_language'),
        ('payments', '0015_auto_20201017_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentUser',
        ),
        migrations.CreateModel(
            name='PaymentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpay_allowed', models.BooleanField()),
                ('tpay_balance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='balance')),
                ('tpay_enabled', models.BooleanField()),
            ],
            options={
                'verbose_name': 'payment user',
                'db_table': 'payments_paymentuser',
                'permissions': (('tpay_allowed', 'Is allowed to use Thalia Pay'),),
                'managed': False,
            },
        ),
    ]
