# Generated by Django 3.1.7 on 2021-03-23 19:27

import os.path

from django.db import migrations

def slurp(file):
    with open(os.path.join(os.path.dirname(__file__), file), 'r') as f:
        return f.read()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_auto_20210323_2121'),
    ]

    operations = [
        migrations.RunSQL(
            sql=slurp('payments_view.sql'),
            reverse_sql="DROP VIEW payments_paymentuser;"
        )
    ]
