# Generated by Django 3.2.4 on 2021-06-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_auto_20210531_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
    ]
