# Generated by Django 3.2.10 on 2021-12-23 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0018_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payable_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payable_object_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
