# Generated by Django 4.1.7 on 2023-03-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0020_alter_payment_paid_by_alter_payment_processed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="moneybird_invoice_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="moneybird invoice id",
            ),
        ),
    ]
