# Generated by Django 4.2 on 2023-05-10 17:22

from django.db import migrations, models
import django.db.models.deletion
import localflavor.generic.models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("payments", "0022_alter_bankaccount_iban"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payable_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payable_object_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
