# Generated by Django 4.2.7 on 2023-11-14 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0047_remove_profile_receive_magazine"),
        ("payments", "0025_alter_payment_processed_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="request timestamp"
                    ),
                ),
                (
                    "required_paid_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="required paid date"
                    ),
                ),
                ("amount", models.FloatField(verbose_name="payment amount")),
                (
                    "topic",
                    models.TextField(max_length=32, verbose_name="payment topic"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="payment notes",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_request_payer",
                        to="payments.paymentuser",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_requester",
                        to="members.member",
                    ),
                ),
            ],
        ),
    ]
