# Generated by Django 5.1.5 on 2025-08-13 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0051_membership_study_long_until'),
        ('payments', '0025_alter_payment_processed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_payment_set', to='members.member', verbose_name='paid by'),
        ),
    ]
