# Generated by Django 5.1.2 on 2024-11-27 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0051_membership_study_long_until'),
        ('payments', '0025_alter_payment_processed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_paid_date', models.DateTimeField(blank=True, null=True, verbose_name='required paid date')),
                ('amount', models.FloatField(verbose_name='payment amount')),
                ('topic', models.TextField(max_length=32, verbose_name='payment topic')),
                ('notes', models.TextField(blank=True, max_length=256, null=True, verbose_name='payment notes')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_request_payer', to='payments.paymentuser')),
                ('payment', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_payment', to='payments.payment')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requester', to='members.member')),
            ],
            options={
                'ordering': ('required_paid_date',),
            },
        ),
    ]
