# Generated by Django 5.2.7 on 2025-11-19 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0051_membership_study_long_until'),
        ('payments', '0026_alter_payment_paid_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_payment_set', to='members.member', verbose_name='paid by'),
        ),
    ]
