# Generated by Django 4.2.7 on 2024-05-29 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0026_paymentrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentrequest",
            options={"ordering": ("required_paid_date",)},
        ),
        migrations.RemoveField(
            model_name="paymentrequest",
            name="created_at",
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="payment",
            field=models.OneToOneField(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="related_payment",
                to="payments.payment",
            ),
        ),
    ]
