# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-07 15:04
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
import localflavor.generic.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('members', '0001_initial'), ('members', '0002_auto_20160707_1512')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(blank=True, choices=[('computingscience', 'Computing Science'), ('informationscience', 'Information Sciences')], max_length=20, null=True, verbose_name='Study programme')),
                ('student_number', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid student- of e/z/u-number.', regex='(s\\d{7}|[ezu]\\d{6,7})')])),
                ('type', models.CharField(choices=[('benefactor', 'Benefactor'), ('member', 'Member'), ('honorary', 'Honorary Member')], max_length=40, verbose_name='Membership type')),
                ('registration_year', models.IntegerField(help_text='The year this member first became a part of Thalia', verbose_name='Registration year')),
                ('membership_expiration', models.DateField(blank=True, help_text='Let the membership expire after this time', null=True, verbose_name='Expiration date of membership')),
                ('address_street', models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Include the house number', regex='^.+ \\d+.*')], verbose_name='Street and house number')),
                ('address_street2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Second address line')),
                ('address_postal_code', models.CharField(max_length=10, null=True, verbose_name='Postal code')),
                ('address_city', models.CharField(max_length=40, null=True, verbose_name='City')),
                ('phone_number', models.CharField(blank=True, help_text='Enter a phone number so Thalia may reach you', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^\\+?\\d+$')], verbose_name='Phone number')),
                ('emergency_contact', models.CharField(blank=True, help_text='Who should we contact in case of emergencies', max_length=255, null=True, verbose_name='Emergency contact name')),
                ('emergency_contact_phone_number', models.CharField(blank=True, help_text='The phone number for the emergency contact', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^\\+?\\d+$')], verbose_name='Emergency contact phone number')),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('show_birthday', models.BooleanField(default=True, help_text='Show the birthday on your profile page and in the birthday calendar', verbose_name='Display birthday')),
                ('website', models.URLField(blank=True, help_text='Website to display on your profile page', null=True, verbose_name='Website')),
                ('profile_description', models.TextField(blank=True, help_text='Text to display on your profile', verbose_name='Profile text')),
                ('nickname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nickname')),
                ('display_name_preference', models.CharField(choices=[('full', 'Show full name'), ('nickname', 'Show only nickname'), ('initials', 'Show initials and last name'), ('fullnick', 'Show name like "John \'nickname\' Doe"'), ('nicklast', 'Show nickname and last name')], default='full', max_length=10, verbose_name='How to display name')),
                ('language', models.CharField(choices=[('en', 'English'), ('nl', 'Dutch')], default='nl', help_text='Preferred language for e.g. news letters', max_length=5, verbose_name='Preferred language')),
                ('receive_optin', models.BooleanField(default=True, help_text="Receive mailings about vacancies and events from Thalia's sponsors.", verbose_name='Receive opt-in mailings')),
                ('direct_debit_authorized', models.BooleanField(choices=[(True, 'Yes, I want Thalia to take the membership fees from my bank account through direct debit for each year.'), (False, 'No, I will pay the contribution myself')], default=False, help_text='Each year, have Thalia take the membership fees from my bank account', verbose_name='Direct debit')),
                ('bank_account', localflavor.generic.models.IBANField(include_countries=('AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GI', 'GR', 'HR', 'HU', 'IE', 'IS', 'IT', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK', 'SM'), blank=True, help_text='Bank account for direct debit', verbose_name='Bank account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
