# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-07-27 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_squashed_0002_auto_20160707_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='public/avatars/', verbose_name='Foto'),
        ),
    ]
