# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-27 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_becomeamemberdocument'),
        ('members', '0002_member_photo'),
    ]

    operations = [
    ]
