# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-06 21:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20160706_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='emergency_contact_phone_number',
            field=models.CharField(blank=True, help_text='The phone number for the emergency contact', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^\\+?\\d+$')], verbose_name='Emergency contact phone number'),
        ),
    ]
