# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0003_merge_20160727_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('member', 'Member'), ('supporter', 'Supporter'), ('honorary', 'Honorary Member')], max_length=40, verbose_name='Membership type')),
                ('since', models.DateField(default=django.utils.timezone.now, help_text='The date the member started holding this membership.', verbose_name='Membership since')),
                ('until', models.DateField(blank=True, help_text='The date the member stops holding this membership.', null=True, verbose_name='Membership until')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_expiration',
        ),
        migrations.RemoveField(
            model_name='member',
            name='registration_year',
        ),
        migrations.RemoveField(
            model_name='member',
            name='type',
        ),
        migrations.AddField(
            model_name='member',
            name='starting_year',
            field=models.IntegerField(blank=True, help_text='The year this member started studying.', null=True, verbose_name='Starting year'),
        ),
    ]
