# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 18:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20160805_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='student_number',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid student- or e/z/u-number.', regex='(s\\d{7}|[ezu]\\d{6,7})')]),
        ),
    ]
