# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20160824_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='public/avatars/', verbose_name='Photo'),
        ),
    ]
