# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20160824_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='receive_newsletter',
            field=models.BooleanField(default=True, help_text='Receive the Thalia Newsletter', verbose_name='Receive newsletter'),
        ),
    ]
