# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20160901_2159'),
        ('members', '0007_member_receive_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='initials',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Initials'),
        ),
    ]
