# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_receive_newsletter'),
        ('members', '0009_auto_20160901_2244'),
    ]

    operations = [
    ]
