# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20161030_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Dutch')], default='nl', help_text='Preferred language for e.g. newsletters', max_length=5, verbose_name='Preferred language'),
        ),
    ]
