# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_member_blacklisted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='blacklisted',
            new_name='event_permissions',
        ),
    ]
