# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20161109_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('user__first_name', 'user__last_name')},
        ),
    ]
