# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 18:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20170120_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='student_number',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid student- or e/z/u-number.', regex='(s\\d{7}|[ezu]\\d{6,7})')], verbose_name='Student number'),
        ),
    ]
