# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0022_4_user_foreign_keys'),
        ('events', '0020_4_user_foreign_keys'),
        ('mailinglists', '0010_4_user_foreign_keys'),
        ('pizzas', '0003_4_user_foreign_keys'),
        ('members', '0016_auto_20170225_1949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Profile',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
