# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('members', '0017_rename_member_to_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
                'ordering': ('first_name', 'last_name'),
            },
            bases=('auth.user',),
        ),
    ]
