# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_create_proxy_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BecomeAMemberDocument',
        ),
    ]
