# Generated by Django 2.0.2 on 2018-03-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_delete_becomeamemberdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_description',
            field=models.TextField(blank=True, help_text='Text to display on your profile', max_length=4096, null=True, verbose_name='Profile text'),
        ),
    ]
