# Generated by Django 2.0.2 on 2018-06-07 11:42

import uuid
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_max_length_on_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('verify_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('confirm_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('verified', models.BooleanField(default=False, help_text='the new email address is valid', verbose_name='verified')),
                ('confirmed', models.BooleanField(default=False, help_text='the old email address was checked', verbose_name='confirmed')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member', verbose_name='member')),
            ],
        ),
    ]
