# Generated by Django 2.0.8 on 2018-08-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_auto_20180708_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='receive_optin',
            field=models.BooleanField(default=True, help_text="Receive mailings about vacancies and events from Thalia's partners.", verbose_name='Receive opt-in mailings'),
        ),
    ]
