# Generated by Django 2.0.8 on 2018-09-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_auto_20180907_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.CharField(choices=[('member', 'Member'), ('supporter', 'Benefactor'), ('honorary', 'Honorary Member')], max_length=40, verbose_name='Membership type'),
        ),
    ]
