# Generated by Django 2.1.5 on 2019-01-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_auto_20181217_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_country',
            field=models.CharField(
                choices=[('AX', 'Åland Islands'), ('AL', 'Albania'),
                         ('AD', 'Andorra'), ('AT', 'Austria'),
                         ('BY', 'Belarus'), ('BE', 'Belgium'),
                         ('BA', 'Bosnia and Herzegovina'), ('BG', 'Bulgaria'),
                         ('HR', 'Croatia'), ('CZ', 'Czechia'),
                         ('DK', 'Denmark'), ('EE', 'Estonia'),
                         ('FO', 'Faroe Islands'), ('FI', 'Finland'),
                         ('FR', 'France'), ('DE', 'Germany'),
                         ('GI', 'Gibraltar'), ('GR', 'Greece'),
                         ('GG', 'Guernsey'), ('VA', 'Vatican City'),
                         ('HU', 'Hungary'), ('IS', 'Iceland'),
                         ('IE', 'Ireland'), ('IM', 'Isle of Man'),
                         ('IT', 'Italy'), ('JE', 'Jersey'), ('LV', 'Latvia'),
                         ('LI', 'Liechtenstein'), ('LT', 'Lithuania'),
                         ('LU', 'Luxembourg'), ('MK', 'Macedonia (FYROM)'),
                         ('MT', 'Malta'), ('MD', 'Moldova'), ('MC', 'Monaco'),
                         ('ME', 'Montenegro'), ('NL', 'Netherlands'),
                         ('NO', 'Norway'), ('PL', 'Poland'),
                         ('PT', 'Portugal'), ('RO', 'Romania'),
                         ('RU', 'Russian Federation'), ('SM', 'San Marino'),
                         ('RS', 'Serbia'), ('SK', 'Slovakia'),
                         ('SI', 'Slovenia'), ('ES', 'Spain'),
                         ('SJ', 'Svalbard and Jan Mayen'), ('SE', 'Sweden'),
                         ('CH', 'Switzerland'), ('UA', 'Ukraine'),
                         ('GB', 'United Kingdom')],
                default='NL', max_length=2, null=True,
                verbose_name='Country'),
            preserve_default=False,
        ),
    ]
