# Generated by Django 2.2 on 2019-04-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_remove_profile_bank_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bank_account',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='direct_debit_authorized',
            new_name='auto_renew',
        ),
        migrations.AlterField(
            model_name='profile',
            name='auto_renew',
            field=models.BooleanField(choices=[(True, 'Yes, enable auto renewal.'), (False, 'No, manual renewal required.')], default=False, verbose_name='Automatically renew membership'),
        ),
    ]
