# Generated by Django 2.2.1 on 2019-06-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_auto_20190428_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('first_name', 'last_name'), 'permissions': (('nextcloud_admin', 'Access NextCloud as admin'),)},
        ),
    ]
