# Generated by Django 2.2.1 on 2019-09-04 17:06

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0034_auto_20190605_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=members.models._profile_image_path, verbose_name='Photo'),
        ),
    ]
