# Generated by Django 2.2.6 on 2019-11-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0035_auto_20190904_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_gsuite_only',
            field=models.BooleanField(default=False, help_text='If you enable this option you will no longer receive emails send to you by Thalia on your personal email address. We will only use your G Suite email address.', verbose_name='Only receive Thalia emails on G Suite-account'),
        ),
    ]
