# Generated by Django 3.0.3 on 2020-02-19 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0036_profile_email_gsuite_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shoe_size',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(39), django.core.validators.MaxValueValidator(47)], verbose_name='Shoe size'),
        ),
    ]
