# Generated by Django 3.0.2 on 2020-04-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0036_profile_email_gsuite_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receive_magazine',
            field=models.BooleanField(default=True, help_text='Receive printed Thabloid magazines', verbose_name='Receive the Thabloid'),
        ),
    ]
