# Generated by Django 3.0.2 on 2020-05-13 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0037_profile_receive_magazine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('first_name', 'last_name')},
        ),
    ]
