# Generated by Django 3.1.1 on 2020-09-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0038_auto_20200513_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
    ]
