# Generated by Django 3.2.10 on 2021-12-15 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_remove_profile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='auto_renew',
        ),
    ]
