# Generated by Django 3.1.3 on 2020-11-23 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_remove_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shoe_size',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(39), django.core.validators.MaxValueValidator(47)], verbose_name='Shoe Size'),
        ),
    ]
