# Generated by Django 3.2.10 on 2021-12-15 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_remove_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shoe_size',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=39, message='Please enter a size between 39 and 47, or leave empty'), django.core.validators.MaxValueValidator(limit_value=47, message='Please enter a size between 39 and 47, or leave empty')]),
        ),
    ]
