# Generated by Django 3.2.12 on 2022-02-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0040_remove_profile_auto_renew'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shoe_size',
            field=models.IntegerField(blank=True, help_text='The size of your shoes :)', null=True, verbose_name='shoe size'),
        ),
    ]
