# Generated by Django 4.1.2 on 2022-10-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0041_alter_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="photo_permissions",
            field=models.BooleanField(
                blank=True,
                help_text="Consent to all your photos being shared across social media platforms.",
                null=True,
                verbose_name="Opt-in social media pictures",
            ),
        ),
    ]
