# Generated by Django 4.1.7 on 2023-02-15 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0042_profile_is_minimized_alter_profile_address_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="shoe_size",
            field=models.IntegerField(
                blank=True,
                help_text="This is how big the feet are. Very important for bowling",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(39),
                    django.core.validators.MaxValueValidator(47),
                ],
                verbose_name="Shoe size",
            ),
        ),
    ]
