# Generated by Django 4.1.5 on 2023-02-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0042_profile_is_minimized_alter_profile_address_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="receive_oldmembers",
            field=models.BooleanField(
                default=True,
                help_text="If you are a past member, receive emails about Thalia events aimed at alumni.",
                verbose_name="Receive alumni emails",
            ),
        ),
    ]
