# Generated by Django 4.1.6 on 2023-02-08 19:37

from django.db import migrations
import members.models.profile
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0042_profile_is_minimized_alter_profile_address_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=thumbnails.fields.ImageField(
                blank=True,
                null=True,
                upload_to=members.models.profile._profile_image_path,
                verbose_name="Photo",
            ),
        ),
    ]
