# Generated by Django 4.1.6 on 2023-02-08 19:37

from django.db import migrations
import members.models.profile
import thumbnails.fields


def create_thumbnail_sources(apps, _):
    Source = apps.get_model("thumbnails", "Source")
    Profile = apps.get_model("members", "Profile")
    for p in Profile.objects.filter(photo__isnull=False).all():
        Source.objects.get_or_create(name=p.photo.name)


class Migration(migrations.Migration):
    dependencies = [
        ("thumbnails", "0001_initial"),
        ("members", "0043_profile_receive_oldmembers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=thumbnails.fields.ImageField(
                blank=True,
                null=True,
                upload_to=members.models.profile._profile_image_path,
                verbose_name="Photo",
            ),
        ),
        migrations.RunPython(create_thumbnail_sources, migrations.RunPython.noop)
    ]
