# Generated by Django 4.1.7 on 2023-03-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0044_alter_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="receive_reg_conf",
            field=models.BooleanField(
                default=True,
                help_text="Receive mailings about your registrations of events from Thalia",
                verbose_name="Receive registration conformations",
            ),
        ),
    ]
