# Generated by Django 4.2.2 on 2023-06-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0045_profile_receive_registration_confirmation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email_gsuite_only",
            field=models.BooleanField(
                default=False,
                help_text="If you enable this option you will no longer receive emails sent to you by Thalia on your personal email address. We will only use your G Suite email address.",
                verbose_name="Only receive Thalia emails on G Suite-account",
            ),
        ),
    ]
