# Generated by Django 4.2 on 2023-05-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0045_profile_receive_registration_confirmation"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="study_long_member",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the member should have a membership for entire study.",
                verbose_name="Membership for study",
            ),
        ),
    ]
