# Generated by Django 4.1.7 on 2023-03-16 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0045_profile_receive_reg_conf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="receive_reg_conf",
            new_name="receive_registration",
        ),
    ]
