# Generated by Django 4.2.2 on 2023-06-22 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0046_alter_profile_email_gsuite_only"),
        ("members", "0046_remove_profile_receive_magazine"),
    ]

    operations = []
