# Generated by Django 4.1.3 on 2023-04-26 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0046_alter_profile_email_gsuite_only"),
        ("thabloid", "0008_thabloid_user_blacklistedthabloiduser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="receive_magazine",
        ),
    ]
