# Generated by Django 4.2.8 on 2024-01-11 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0048_auto_20231121_2025"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="since",
            field=models.DateField(
                default=datetime.date.today,
                help_text="The date the member started holding this membership.",
                verbose_name="Membership since",
            ),
        ),
    ]
