# Generated by Django 5.0.7 on 2024-10-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0049_alter_membership_since"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="study_long",
            field=models.BooleanField(
                default=False,
                help_text="Whether the member has paid to be member throughout their studies.",
                verbose_name="Study long",
            ),
        ),
    ]
