# Generated by Django 4.2.8 on 2024-02-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0049_alter_membership_since"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=models.DateField(
                blank=True,
                help_text="Please use the following format: dd/mm/yyyy",
                null=True,
                verbose_name="Birthday",
            ),
        ),
    ]
