# Generated by Django 5.0.6 on 2024-06-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0050_profile_optin_sharing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="optin_sharing",
            field=models.BooleanField(
                help_text="Do you give permission to post photos that you are on of events on social media?",
                null=True,
                verbose_name="Opt-in sharing photos on social media",
            ),
        ),
    ]
