# Generated by Django 4.1.7 on 2023-02-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "_synced_with_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Latest changes have been pushed to Moneybird.",
                        verbose_name="Synced with Moneybird",
                    ),
                ),
                (
                    "_delete_from_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Delete this object from Moneybird when syncing.",
                        verbose_name="To be deleted from Moneybird",
                    ),
                ),
                (
                    "moneybird_version",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Moneybird version"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="company name",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="last name"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
