# Generated by Django 4.1.7 on 2023-04-07 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moneybirdsynchronization", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moneybirdcontact",
            name="moneybird_version",
        ),
    ]
