# Generated by Django 4.1.7 on 2023-04-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moneybirdsynchronization", "0002_remove_moneybirdcontact_moneybird_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moneybirdcontact",
            name="moneybird_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Moneybird ID"
            ),
        ),
    ]
