# Generated by Django 4.1.7 on 2023-02-22 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "moneybirdsynchronization",
            "0002_remove_contact_company_name_contact_address1_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="address1",
            new_name="address_1",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="address2",
            new_name="address_2",
        ),
    ]
