# Generated by Django 4.2.5 on 2023-09-11 19:45

from django.conf import settings
from django.db import migrations, models

from moneybirdsynchronization.moneybird import get_moneybird_api_service


def create_moneybird_projects(apps, schema_editor):
    MoneybirdProject = apps.get_model("moneybirdsynchronization", "MoneybirdProject")

    if not settings.MONEYBIRD_SYNC_ENABLED:
        return None

    moneybird = get_moneybird_api_service()

    # Get all projects from the API.
    projects = []
    while True:
        page = moneybird._administration.get("projects", params={"per_page": 100})
        projects.extend(page)
        if len(page) < 100:
            break

    # Create a MoneybirdProject for each project.
    for project in projects:
        MoneybirdProject.objects.get_or_create(
            name=project["name"],
            moneybird_id=project["id"],
        )


class Migration(migrations.Migration):
    dependencies = [
        ("moneybirdsynchronization", "0003_alter_moneybirdcontact_moneybird_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneybirdProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="Name"
                    ),
                ),
                (
                    "moneybird_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Moneybird ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "moneybird project",
                "verbose_name_plural": "moneybird projects",
            },
        ),
    ]
