# Generated by Django 4.1.7 on 2023-02-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "moneybirdsynchronization",
            "0004_remove_contact__delete_from_moneybird_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="moneybird_version",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Moneybird version"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="moneybird_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Moneybird ID"
            ),
        ),
    ]
