# Generated by Django 4.2.6 on 2023-10-19 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("moneybirdsynchronization", "0004_moneybirdproject"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneybirdSalesInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                (
                    "moneybird_invoice_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="moneybird invoice id",
                    ),
                ),
                (
                    "moneybird_details_attribute_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="moneybird details attribute id",
                    ),
                ),
                (
                    "payable_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "moneybird sales invoice",
                "verbose_name_plural": "moneybird sales invoices",
                "unique_together": {("payable_model", "object_id")},
            },
        ),
    ]
