# Generated by Django 4.2.5 on 2023-10-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moneybirdsynchronization", "0004_moneybirdproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="moneybirdcontact",
            name="moneybird_has_mandate",
            field=models.BooleanField(default=False),
        ),
    ]
