# Generated by Django 4.2.5 on 2023-10-20 09:12

from django.db import migrations, models


def set_needs_synchronization_false(apps, schema_editor):
    MoneybirdExternalInvoice = apps.get_model(
        "moneybirdsynchronization", "MoneybirdExternalInvoice"
    )
    MoneybirdExternalInvoice.objects.all().update(needs_synchronization=False)


class Migration(migrations.Migration):
    dependencies = [
        (
            "moneybirdsynchronization",
            "0005_moneybirdcontact_moneybird_sepa_mandate_id",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="moneybirdexternalinvoice",
            name="needs_synchronization",
            field=models.BooleanField(
                default=True,
                help_text="Indicates that the invoice has to be synchronized (again).",
            ),
        ),
        migrations.AddField(
            model_name="moneybirdexternalinvoice",
            name="needs_deletion",
            field=models.BooleanField(
                default=False,
                help_text="Indicates that the invoice has to be deleted from moneybird.",
            ),
        ),
        migrations.RunPython(
            set_needs_synchronization_false,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
