# Generated by Django 4.2.6 on 2023-10-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moneybirdsynchronization", "0005_moneybirdcontact_moneybird_has_mandate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moneybirdcontact",
            name="moneybird_has_mandate",
        ),
        migrations.AddField(
            model_name="moneybirdcontact",
            name="moneybird_sepa_mandate_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Moneybird SEPA mandate ID",
            ),
        ),
    ]
