# Generated by Django 4.2.5 on 2023-10-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "moneybirdsynchronization",
            "0006_moneybirdexternalinvoice_needs_synchronization",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="moneybirdpayment",
            name="moneybird_financial_mutation_id",
            field=models.CharField(
                default="0",
                max_length=255,
                verbose_name="moneybird financial mutation id",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="moneybirdpayment",
            name="moneybird_financial_statement_id",
            field=models.CharField(
                default="0",
                max_length=255,
                verbose_name="moneybird financial statement id",
            ),
            preserve_default=False,
        ),
    ]
