# Generated by Django 4.2.5 on 2023-10-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "moneybirdsynchronization",
            "0006_remove_moneybirdcontact_moneybird_has_mandate_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="moneybirdexternalinvoice",
            name="needs_synchronization",
            field=models.BooleanField(
                default=False,
                help_text="Indicates that the invoice has to be synchronized (again).",
            ),
        ),
    ]
