# Generated by Django 4.2.6 on 2023-10-24 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moneybirdsynchronization", "0005_moneybirdsalesinvoice"),
        (
            "moneybirdsynchronization",
            "0006_remove_moneybirdcontact_moneybird_has_mandate_and_more",
        ),
    ]

    operations = []
