# Generated by Django 4.2.7 on 2023-11-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "moneybirdsynchronization",
            "0007_alter_moneybirdpayment_moneybird_financial_mutation_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="moneybirdcontact",
            name="needs_synchronization",
            field=models.BooleanField(
                default=True,
                help_text="Indicates that the contact has to be synchronized (again).",
            ),
        ),
    ]
