# Generated by Django 4.2.6 on 2023-11-01 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0007_alter_productlistitem_options_and_more"),
        (
            "moneybirdsynchronization",
            "0007_alter_moneybirdpayment_moneybird_financial_mutation_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneybirdGeneralJournalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_general_journal_document_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="moneybird general journal document id",
                    ),
                ),
                (
                    "needs_synchronization",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates that the journal has to be synchronized (again).",
                    ),
                ),
                (
                    "needs_deletion",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates that the journal has to be deleted from moneybird.",
                    ),
                ),
                (
                    "moneybird_details_debit_attribute_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="moneybird details attribute id (debit)",
                    ),
                ),
                (
                    "moneybird_details_credit_attribute_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="moneybird details attribute id (credit)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoneybirdMerchandiseSaleJournal",
            fields=[
                (
                    "moneybirdgeneraljournaldocument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="moneybirdsynchronization.moneybirdgeneraljournaldocument",
                    ),
                ),
                (
                    "external_invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="moneybird_journal_external_invoice",
                        to="moneybirdsynchronization.moneybirdexternalinvoice",
                        verbose_name="external invoice",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "moneybird general journal document",
                "verbose_name_plural": "moneybird general journal documents",
            },
            bases=("moneybirdsynchronization.moneybirdgeneraljournaldocument",),
        ),
    ]
