# Generated by Django 4.2.6 on 2023-10-24 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moneybirdsynchronization", "0005_moneybirdsalesinvoice"),
        (
            "moneybirdsynchronization",
            "0007_alter_moneybirdpayment_moneybird_financial_mutation_id_and_more",
        ),
    ]

    operations = []
