# Generated by Django 4.2.6 on 2023-10-26 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0007_alter_productlistitem_options_and_more"),
        (
            "moneybirdsynchronization",
            "0007_alter_moneybirdpayment_moneybird_financial_mutation_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneybirdMerchandiseSaleJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_general_journal_document_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="moneybird general journal document id",
                    ),
                ),
                (
                    "external_invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="moneybird_journal_external_invoice",
                        to="moneybirdsynchronization.moneybirdexternalinvoice",
                        verbose_name="external invoice",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "moneybird merchandise sale journal",
                "verbose_name_plural": "moneybird merchandise sale journals",
            },
        ),
    ]
