# Generated by Django 4.2.6 on 2023-10-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moneybirdsynchronization", "0008_moneybirdmerchandisesalejournal"),
    ]

    operations = [
        migrations.AddField(
            model_name="moneybirdmerchandisesalejournal",
            name="needs_deletion",
            field=models.BooleanField(
                default=False,
                help_text="Indicates that the journal has to be deleted from moneybird.",
            ),
        ),
        migrations.AddField(
            model_name="moneybirdmerchandisesalejournal",
            name="needs_synchronization",
            field=models.BooleanField(
                default=True,
                help_text="Indicates that the journal has to be synchronized (again).",
            ),
        ),
    ]
