# Generated by Django 5.1.2 on 2025-01-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybirdsynchronization', '0008_moneybirdcontact_needs_synchronization'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneybirdReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneybird_receipt_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='moneybird receipt id')),
                ('moneybird_attachment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='moneybird attachment id')),
            ],
            options={
                'verbose_name': 'moneybird receipt',
                'verbose_name_plural': 'moneybird receipt',
            },
        ),
    ]
