# Generated by Django 5.1.2 on 2025-01-19 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybirdsynchronization', '0009_moneybirdreceipt'),
        ('reimbursements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneybirdreceipt',
            name='reimbursement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reimbursements.reimbursement'),
        ),
    ]
