# Generated by Django 4.2.6 on 2023-10-26 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "moneybirdsynchronization",
            "0009_moneybirdsalesinvoice_needs_deletion_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="MoneybirdSalesInvoice",
        ),
    ]
