# Generated by Django 5.1.5 on 2025-05-10 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybirdsynchronization', '0010_moneybirdreceipt_reimbursement'),
        ('reimbursements', '0002_remove_reimbursement_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneybirdreceipt',
            name='reimbursement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moneybird_receipt', to='reimbursements.reimbursement'),
        ),
    ]
