# Generated by Django 5.1.5 on 2025-07-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybirdsynchronization', '0011_alter_moneybirdreceipt_reimbursement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneybirdreceipt',
            name='moneybird_attachment_id',
        ),
        migrations.AddField(
            model_name='moneybirdreceipt',
            name='moneybird_attachment_is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
