# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0004_auto_20160805_1435'),
        ('events', '0003_remove_event_registration_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, help_text='Use this for non-members', max_length=50, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Order from')),
                ('end', models.DateTimeField(verbose_name='Order until')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('available', models.BooleanField(default=True)),
                ('description_en', models.TextField(verbose_name='description (EN)')),
                ('description_nl', models.TextField(verbose_name='description (NL)')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pizza_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzas.PizzaEvent'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizzas.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('pizza_event', 'member')]),
        ),
    ]
