# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_3_user_foreign_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='member_old',
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('pizza_event', 'member')},
        ),
    ]
