# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 18:54
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_auto_20171013_1408'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('available_products', django.db.models.manager.Manager()),
            ],
        ),
    ]
