# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_product_restricted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': (('order_restricted_products', 'Order restricted products'),)},
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
    ]
