# Generated by Django 2.1.3 on 2018-12-19 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotifications', '0013_auto_20181111_1319'),
        ('pizzas', '0006_product_restricted_squashed_0008_auto_20180102_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaevent',
            name='end_reminder',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pushnotifications.ScheduledMessage'),
        ),
        migrations.AddField(
            model_name='pizzaevent',
            name='send_notification',
            field=models.BooleanField(default=True, verbose_name='Send an order notification'),
        ),
    ]
