# Generated by Django 2.0.6 on 2018-08-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_product_restricted_squashed_0008_auto_20180102_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaevent',
            name='send_notification',
            field=models.BooleanField(default=True, verbose_name='Send an order notification'),
        ),
        migrations.AddField(
            model_name='pizzaevent',
            name='task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
