# Generated by Django 2.2 on 2019-04-13 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190204_2111'),
        ('pizzas', '0007_auto_20181219_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pizzas_order', to='payments.Payment', verbose_name='payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, help_text='Use this for non-members', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzas.PizzaEvent', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizzas.Product', verbose_name='product'),
        ),
    ]
