# Generated by Django 3.1.1 on 2020-09-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0012_auto_20191116_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_nl',
        ),
    ]
