# Generated by Django 3.2 on 2021-05-09 11:11

from django.db import migrations, models
import django.db.models.deletion
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotifications', '0018_auto_20200907_1835'),
        ('payments', '0015_auto_20201017_1354'),
        ('events', '0046_event_shift'),
        ('members', '0039_remove_profile_language'),
        ('pizzas', '0013_remove_product_description_nl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='FoodOrder',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_en',
            new_name='description'
        ),
        migrations.RenameModel(
            old_name='PizzaEvent',
            new_name='FoodEvent',
        ),
        migrations.RenameField(
            model_name='foodorder',
            old_name='pizza_event',
            new_name='food_event'
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='food_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='pizzas.foodevent', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food_order', to='payments.payment', verbose_name='payment'),
        ),
        migrations.AlterUniqueTogether(
            name='foodorder',
            unique_together={('food_event', 'member')},
        ),
        migrations.AlterField(
            model_name='foodevent',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_event',
                                       to='events.event'),
        ),
    ]
