# Generated by Django 3.2.4 on 2021-06-22 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_alter_payment_options'),
        ('pizzas', '0015_foodevent_tpay_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_order', to='payments.payment', verbose_name='payment'),
        ),
    ]
