# Generated by Django 4.1.6 on 2023-02-03 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pizzas", "0017_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodevent",
            name="end_reminder",
        ),
    ]
