# Generated by Django 5.1.5 on 2025-08-13 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0051_membership_study_long_until'),
        ('pizzas', '0018_remove_foodevent_end_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member'),
        ),
    ]
