# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='until',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
