# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20161109_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.CharField(choices=[('document', 'Document'), ('exam', 'Exam'), ('partial', 'Partial Exam'), ('resit', 'Resit'), ('practice', 'Practice Exam'), ('answers', 'Exam Answers')], max_length=40, verbose_name='exam type'),
        ),
    ]
