# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20170225_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='file',
            field=models.FileField(help_text="Use the 'View on site' button to download the file for inspection.", upload_to='education/files/exams/'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='file',
            field=models.FileField(help_text="Use the 'View on site' button to download the file for inspection.", upload_to='education/files/summary/'),
        ),
    ]
