# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20170227_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.CharField(choices=[('document', 'Document'), ('exam', 'Exam'), ('partial', 'Partial Exam'), ('resit', 'Resit'), ('practice', 'Practice Exam'), ('exam_answers', 'Exam Answers'), ('partial_answers', 'Partial Exam Answers'), ('resit_answers', 'Resit Answers'), ('practice_answers', 'Practice Exam Answers')], max_length=40, verbose_name='exam type'),
        ),
    ]
