# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_create_proxy_member'),
        ('education', '0005_auto_20170906_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member', verbose_name='uploader'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member', verbose_name='uploader'),
        ),
    ]
