# Generated by Django 2.0.5 on 2018-05-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_rename_answers_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='download_count',
            field=models.IntegerField(default=0, verbose_name='amount of downloads'),
        ),
        migrations.AddField(
            model_name='summary',
            name='download_count',
            field=models.IntegerField(default=0, verbose_name='amount of downloads'),
        ),
    ]
