# Generated by Django 2.2.1 on 2019-08-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_auto_20190130_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='period',
        ),
        migrations.RemoveField(
            model_name='course',
            name='shorthand_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='shorthand_nl',
        ),
    ]
