# Generated by Django 2.2.9 on 2020-01-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0011_auto_20190803_1857"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-pk"],
                "verbose_name": "course",
                "verbose_name_plural": "courses",
            },
        ),
    ]
