# Generated by Django 3.1.1 on 2020-09-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_auto_20200125_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_nl',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name_nl',
        ),
    ]
