# Generated by Django 4.2 on 2023-04-13 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0044_alter_profile_photo"),
        ("education", "0015_alter_exam_uploader_alter_summary_uploader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="uploader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="members.member",
                verbose_name="uploader",
            ),
        ),
        migrations.AlterField(
            model_name="summary",
            name="uploader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="members.member",
                verbose_name="uploader",
            ),
        ),
    ]
