# Generated by Django 4.2.8 on 2024-01-11 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0016_alter_exam_uploader_alter_summary_uploader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="uploader_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="summary",
            name="uploader_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
