# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-23 10:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationDocumentsYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1990)])),
                ('policy_document', models.FileField(blank=True, upload_to='documents/association/', validators=[])),
                ('annual_report', models.FileField(blank=True, upload_to='documents/association/', validators=[])),
                ('financial_report', models.FileField(blank=True, upload_to='documents/association/', validators=[])),
            ],
        ),
        migrations.DeleteModel(
            name='AssociationDocument',
        ),
    ]
