# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-24 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20160723_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscellaneousDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/miscellaneous/', validators=[])),
                ('members_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='GenericDocument',
        ),
    ]
