# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-07-25 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20160724_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalmeeting',
            options={'ordering': ['datetime']},
        ),
    ]
