# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 09:16
from __future__ import unicode_literals

from django.db import migrations, models

def meetingdocument_upload_to(instance, filename):
    return 'documents/meetings/{}/files/{}'.format(instance.meeting.pk,
                                                   filename)


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20160725_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmeetingdocument',
            name='file',
            field=models.FileField(upload_to=meetingdocument_upload_to, validators=[]),
        ),
    ]
