# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20160813_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmeeting',
            name='minutes',
            field=models.FileField(blank=True, upload_to='documents/meetings/minutes/', validators=[utils.validators.validate_file_extension]),
        ),
    ]
