# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20160907_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmeeting',
            name='minutes',
            field=models.FileField(blank=True, null=True, upload_to='documents/meetings/minutes/', validators=[]),
        ),
    ]
