# Generated by Django 2.0.8 on 2018-11-28 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0036_auto_20181024_1939'),
        ('documents', '0008_2_refactor_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activemembers.MemberGroup', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'event document',
                'verbose_name_plural': 'event documents',
            },
            bases=('documents.document',),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('annual', 'Annual document'), ('association', 'Association document'), ('event', 'Event document'), ('minutes', 'Minutes'), ('misc', 'Miscellaneous document')], default='misc', max_length=40, verbose_name='category'),
        ),
    ]
