# Generated by Django 2.1.7 on 2019-03-27 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_auto_20181219_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_en',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['.txt', '.pdf', '.jpg', '.jpeg', '.png'])], verbose_name='file (EN)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_nl',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['.txt', '.pdf', '.jpg', '.jpeg', '.png'])], verbose_name='file (NL)'),
        ),
    ]
