# Generated by Django 2.2.9 on 2020-01-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20190516_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miscellaneousdocument',
            options={'ordering': ['-created'], 'verbose_name': 'Miscellaneous document', 'verbose_name_plural': 'Miscellaneous documents'},
        ),
    ]
