# Generated by Django 3.1.1 on 2020-09-30 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_auto_20200907_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file_en',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='name_en',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='generalmeeting',
            old_name='location_en',
            new_name='location'
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[
                django.core.validators.FileExtensionValidator(['txt', 'pdf', 'jpg', 'jpeg', 'png'])],
                                   verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='generalmeeting',
            name='location',
            field=models.CharField(max_length=200, verbose_name='location'),
        ),
    ]
