# Generated by Django 3.2.10 on 2021-12-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_remove_multilang_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='members_only',
            field=models.BooleanField(default=True, verbose_name='members only'),
        ),
    ]
