# Generated by Django 5.1.5 on 2025-02-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_delete_eventdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualdocument',
            name='subcategory',
            field=models.CharField(choices=[('report', 'Annual report'), ('financial', 'Financial report'), ('policy', 'Policy document'), ('semi-report', 'Semi-annual report'), ('semi-financial', 'Semi-annual financial report')], default='report', max_length=40, verbose_name='category'),
        ),
    ]
