# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-13 13:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0001_squashed_0006_auto_20160707_1700'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='committee',
            managers=[
                ('active_committees', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='contact_email',
            field=models.EmailField(default='commissie@thalia.nu', max_length=254, verbose_name='contact email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='committee',
            name='since',
            field=models.DateField(blank=True, null=True, verbose_name='founded in'),
        ),
        migrations.AddField(
            model_name='committee',
            name='until',
            field=models.DateField(blank=True, null=True, verbose_name='existed until'),
        ),
        migrations.AlterField(
            model_name='committeemembership',
            name='since',
            field=models.DateField(default=datetime.date.today, help_text='The date this member joined the committee in this role', verbose_name='Committee member since'),
        ),
    ]
