# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-13 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0002_auto_20160713_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('committee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activemembers.Committee')),
                ('is_board', models.BooleanField(default=True, verbose_name='Is this a board')),
            ],
            bases=('activemembers.committee',),
        ),
        migrations.AddField(
            model_name='committeemembership',
            name='role',
            field=models.CharField(blank=True, help_text='The role of this member', max_length=255, null=True, verbose_name='role'),
        ),
    ]
