# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-07-27 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0003_auto_20160713_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='photo',
            field=models.ImageField(upload_to='public/committeephotos/', verbose_name='Image'),
        ),
    ]
