# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20160824_2041'),
        ('activemembers', '0006_auto_20160817_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('members', models.ManyToManyField(to='members.Member')),
            ],
        ),
    ]
