# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


def forwards_func(apps, schema_editor):
    Committee = apps.get_model("activemembers", "committee")
    db_alias = schema_editor.connection.alias
    for committee in Committee.unfiltered_objects.using(db_alias).all():
        committee.name_en = committee.name_nl
        committee.description_en = committee.description_nl
        committee.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0008_auto_20160906_1015'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='committee',
            managers=[
                ('unfiltered_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField('committee', 'name', 'name_nl'),
        migrations.RenameField('committee', 'description', 'description_nl'),
        migrations.AddField(
            model_name='committee',
            name='name_en',
            field=models.CharField(default='', max_length=40, unique=True,
                                   verbose_name='Committee name (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='committee',
            name='name_nl',
            field=models.CharField(max_length=40, unique=True,
                                   verbose_name='Committee name (NL)'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='committee',
            name='description_en',
            field=models.TextField(default='', verbose_name='Description (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='committee',
            name='description_nl',
            field=models.TextField(verbose_name='Description (NL)'),
            preserve_default=True,
        ),
        migrations.RenameField('committeemembership', 'role', 'role_nl'),
        migrations.AddField(
            model_name='committeemembership',
            name='role_en',
            field=models.CharField(blank=True, help_text='The role of this member', max_length=255, null=True, verbose_name='role (EN)'),
        ),
        migrations.AlterField(
            model_name='committeemembership',
            name='role_nl',
            field=models.CharField(blank=True, help_text='The role of this member', max_length=255, null=True, verbose_name='role (NL)'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
