# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0009_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorship',
            name='members',
        ),
        migrations.DeleteModel(
            name='Mentorship',
        ),
    ]
