# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activemembers', '0009_auto_20160906_1931'),
    ]

    def forwards_func(apps, schema_editor):
        Committee = apps.get_model("activemembers", "committee")
        db_alias = schema_editor.connection.alias
        for committee in Committee.unfiltered_objects.using(db_alias).all():
            committee.name_en = committee.name_nl
            committee.description_en = committee.description_nl
            committee.save()

    def reverse_func(apps, schema_editor):
        pass

    operations = [
        migrations.RenameField('committee', 'name', 'name_nl'),
        migrations.RenameField('committee', 'description', 'description_nl'),
        migrations.AddField(
            model_name='committee',
            name='name_en',
            field=models.CharField(default='', max_length=40, unique=True,
                                   verbose_name='Committee name (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='committee',
            name='name_nl',
            field=models.CharField(max_length=40, unique=True,
                                   verbose_name='Committee name (NL)'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='committee',
            name='description_en',
            field=models.TextField(default='', verbose_name='Description (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='committee',
            name='description_nl',
            field=models.TextField(verbose_name='Description (NL)'),
            preserve_default=True,
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
