# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 19:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_merge_20160907_2042'),
        ('activemembers', '0010_auto_20161005_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=django.core.validators.MinValueValidator(1990))),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member', verbose_name='Member')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mentorship',
            unique_together=set([('member', 'year')]),
        ),
    ]
