# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0011_auto_20161005_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='wiki_namespace',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Wiki namespace'),
        ),
    ]
