# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0012_committee_wiki_namespace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-since']},
        ),
    ]
