# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0013_auto_20161123_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
