# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 13:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0015_datamigration_lifelong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorship',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1990)]),
        ),
    ]
