# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0015_datamigration_lifelong'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee',
            options={'ordering': ('name_nl',), 'verbose_name': 'committee', 'verbose_name_plural': 'committees'},
        ),
    ]
