# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0016_auto_20170120_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee',
            options={'verbose_name': 'committee', 'verbose_name_plural': 'committees'},
        ),
    ]
