# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0016_auto_20170124_1431'),
        ('activemembers', '0017_auto_20170121_1105'),
    ]

    operations = [
    ]
