# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0018_merge_20170125_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-since'], 'permissions': (('board_wiki', 'Access the board wiki'),)},
        ),
    ]
