# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglists', '0009_auto_20170429_2149'),
        ('activemembers', '0019_auto_20170227_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='contact_email',
        ),
        migrations.AddField(
            model_name='committee',
            name='contact_mailinglist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailinglists.MailingList', verbose_name='contact email address'),
        ),
    ]
