# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0020_committee_contact_mailinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='contact email address'),
        ),
    ]
