# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0021_auto_20170705_1902'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentorship',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='committee',
            name='members_old',
            field=models.ManyToManyField(through='activemembers.CommitteeMembership', to='members.Member', null=True, related_name='members_old'),
        ),
        migrations.AddField(
            model_name='committeemembership',
            name='member_old',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member', verbose_name='Member', null=True),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='member_old',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member', verbose_name='Member', null=True),
        ),
    ]
