# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0022_3_user_foreign_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='members_old',
        ),
        migrations.RemoveField(
            model_name='committeemembership',
            name='member_old',
        ),
        migrations.RemoveField(
            model_name='mentorship',
            name='member_old',
        ),
        migrations.AlterUniqueTogether(
            name='mentorship',
            unique_together={('member', 'year')},
        ),
    ]
