# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0022_1_user_foreign_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='members',
        ),
        migrations.RemoveField(
            model_name='committeemembership',
            name='member',
        ),
        migrations.RemoveField(
            model_name='mentorship',
            name='member',
        ),
        migrations.AddField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(through='activemembers.CommitteeMembership', to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='committeemembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Member', null=True),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Member', null=True),
        ),
    ]
