# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_create_proxy_member'),
        ('activemembers', '0022_4_user_foreign_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(through='activemembers.CommitteeMembership', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='committeemembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member', verbose_name='Member'),
        ),
    ]
