# Generated by Django 2.0rc1 on 2017-11-29 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0023_auto_20171013_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='contact_mailinglist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailinglists.MailingList', verbose_name='contact mailing list'),
        ),
    ]
