# Generated by Django 2.0.1 on 2018-01-08 11:53

import activemembers.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0024_auto_20171129_2129'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='board',
            managers=[
                ('objects', activemembers.models.BoardManager()),
            ],
        ),
    ]
