# Generated by Django 2.0.8 on 2018-09-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activemembers', '0027_auto_20180901_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.IntegerField(null=True)),
            ],
        ),
    ]
