# Generated by Django 2.0.8 on 2018-09-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0029_save_board_pk_in_tmp'),
    ]

    operations = [
        migrations.DeleteModel(name='Board')
    ]
