# Generated by Django 2.0.8 on 2018-09-01 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('activemembers', '0030_delete_original_board_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Committee',
            new_name='MemberGroup',
        ),
    ]
