# Generated by Django 2.0.8 on 2018-09-01 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activemembers', '0031_rename_base_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membergroup',
            old_name='wiki_namespace',
            new_name='wiki_namespace_old',
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('membergroup_ptr', models.OneToOneField(auto_created=True,
                                                         on_delete=django.db.models.deletion.CASCADE,
                                                         parent_link=True,
                                                         primary_key=True,
                                                         serialize=False,
                                                         to='activemembers.MemberGroup')),
            ],
            options={'ordering': ['-since'],
                     'permissions': (('board_wiki', 'Access the board wiki'),),
                     'verbose_name': 'board', 'verbose_name_plural': 'boards'},
            bases=('activemembers.membergroup',),
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('membergroup_ptr', models.OneToOneField(auto_created=True,
                                                         on_delete=django.db.models.deletion.CASCADE,
                                                         parent_link=True,
                                                         primary_key=True,
                                                         serialize=False,
                                                         to='activemembers.MemberGroup')),
                ('wiki_namespace',
                 models.CharField(blank=True, max_length=50, null=True,
                                  verbose_name='Wiki namespace')),
            ],
            options={
                'verbose_name': 'committee',
                'verbose_name_plural': 'committees',
            },
            bases=('activemembers.membergroup',),
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('membergroup_ptr', models.OneToOneField(auto_created=True,
                                                         on_delete=django.db.models.deletion.CASCADE,
                                                         parent_link=True,
                                                         primary_key=True,
                                                         serialize=False,
                                                         to='activemembers.MemberGroup')),
            ],
            options={
                'verbose_name': 'society',
                'verbose_name_plural': 'societies',
            },
            bases=('activemembers.membergroup',),
        ),
        migrations.AlterModelOptions(
            name='membergroup',
            options={'verbose_name': 'member group',
                     'verbose_name_plural': 'member groups'},
        ),
        migrations.AlterModelManagers(
            name='membergroup',
            managers=[
            ],
        ),
    ]
