# Generated by Django 2.0.8 on 2018-09-01 15:39

from django.db import migrations


def migrate_to(apps, schema_editor):
    TemporaryBoard = apps.get_model("activemembers", "TemporaryBoard")
    MemberGroup = apps.get_model("activemembers", "MemberGroup")

    boards = TemporaryBoard.objects.all()
    for temp_board in boards:
        schema_editor.execute(
            'INSERT INTO activemembers_board (membergroup_ptr_id) VALUES ({});'
            .format(temp_board.parent))

    groups = MemberGroup.objects.all()
    for group in groups:
        if not TemporaryBoard.objects.filter(parent=group.pk).exists():
            schema_editor.execute(
                'INSERT INTO activemembers_committee '
                '(membergroup_ptr_id, wiki_namespace) VALUES ({}, {});'
                .format(group.pk, group.wiki_namespace_old if group.wiki_namespace_old else 'NULL'))


def migrate_back(apps, schema_editor):
    schema_editor.execute('DELETE FROM activemembers_board;')
    Committee = apps.get_model("activemembers", "Committee")
    committees = Committee.objects.all()
    for committee in committees:
        schema_editor.execute(
            'UPDATE activemembers_membergroup '
            'SET wiki_namespace_old={} WHERE id={}'
            .format(committee.wiki_namespace if committee.wiki_namespace else 'NULL', committee.membergroup_ptr_id))
    schema_editor.execute('DELETE FROM activemembers_committee;')


class Migration(migrations.Migration):
    dependencies = [
        ('activemembers', '0032_create_submodels'),
    ]

    operations = [
        migrations.RunPython(migrate_to, migrate_back),
    ]
