# Generated by Django 2.0.8 on 2018-09-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0033_fill_submodel_schemas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryBoard',
        ),
        migrations.RemoveField(model_name='MemberGroup',
                               name='wiki_namespace_old')
    ]
