# Generated by Django 2.0.9 on 2018-10-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0035_auto_20181011_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membergroup',
            name='active',
            field=models.BooleanField(default=False, help_text='This should only be unchecked if the committee has been dissolved. The websites assumes that any committees on it existed at some point.'),
        ),
    ]
