# Generated by Django 3.0.2 on 2020-05-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0037_membergroup_display_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-since'], 'verbose_name': 'board', 'verbose_name_plural': 'boards'},
        ),
        migrations.RemoveField(
            model_name='committee',
            name='wiki_namespace',
        ),
    ]
