# Generated by Django 3.1.1 on 2020-09-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0038_auto_20200513_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membergroup',
            name='description_nl',
        ),
        migrations.RemoveField(
            model_name='membergroup',
            name='name_nl',
        ),
        migrations.RemoveField(
            model_name='membergroupmembership',
            name='role_nl',
        ),
    ]
