# Generated by Django 3.1.1 on 2020-09-09 18:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0039_auto_20200907_1835'),
    ]

    operations = [
        migrations.RenameField(model_name='membergroup', old_name='description_en', new_name='description'),
        migrations.RenameField(model_name='membergroup', old_name='name_en', new_name='name'),
        migrations.RenameField(model_name='membergroupmembership', old_name='role_en', new_name='role'),
        migrations.AlterField(
            model_name='membergroup',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='membergroup',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='membergroupmembership',
            name='role',
            field=models.CharField(blank=True, help_text='The role of this member', max_length=255, null=True,
                                   verbose_name='role'),
        ),
    ]
