# Generated by Django 3.1.1 on 2020-09-09 18:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('activemembers', '0039_auto_20200907_1835'),
    ]

    operations = [
        migrations.RenameField(model_name='membergroup', old_name='description_en', new_name='description'),
        migrations.RenameField(model_name='membergroup', old_name='name_en', new_name='name'),
        migrations.RenameField(model_name='membergroupmembership', old_name='role_en', new_name='role'),
    ]
