# Generated by Django 4.1.6 on 2023-02-08 19:37

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ("activemembers", "0041_alter_membergroup_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membergroup",
            name="photo",
            field=thumbnails.fields.ImageField(
                blank=True,
                null=True,
                upload_to="committeephotos/",
                verbose_name="Image",
            ),
        ),
    ]
