# Generated by Django 4.2.5 on 2023-09-18 07:54

from django.db import migrations, models


def populate_has_chair_permissions(apps, schema_editor):
    MemberGroupMembership = apps.get_model("activemembers", "MemberGroupMembership")
    MemberGroupMembership.objects.filter(chair=True).update(has_chair_permissions=True)


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("activemembers", "0042_alter_membergroup_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="membergroup",
            name="chair_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Permissions only for certain members of a committee",
                related_name="chair_permissions_groups",
                to="auth.permission",
                verbose_name="chair permissions",
            ),
        ),
        migrations.AddField(
            model_name="membergroupmembership",
            name="has_chair_permissions",
            field=models.BooleanField(
                default=False,
                help_text="Give this member chair permission",
                verbose_name="Person with chair permissions",
            ),
        ),
        migrations.AlterField(
            model_name="membergroup",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="permissions_groups",
                to="auth.permission",
                verbose_name="permissions",
            ),
        ),
        migrations.RunPython(populate_has_chair_permissions, migrations.RunPython.noop),
    ]
