# Generated by Django 4.2 on 2023-04-05 18:44

from django.db import migrations
from django.db import models


def migrate_to_authgroups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    MemberGroup = apps.get_model("activemembers", "MemberGroup")
    MemberGroupMembership = apps.get_model("activemembers", "MemberGroupMembership")

    for membergroup in MemberGroup.objects.all():
        group = Group.objects.create(name=membergroup.name)
        group.permissions.set(membergroup.permissions.all())
        membergroup.group_ptr = group.pk
        membergroup.save()
        MemberGroupMembership.objects.filter(group=membergroup).update(membergroup=group)


class Migration(migrations.Migration):
    dependencies = [
        ("activemembers", "0042_alter_membergroup_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="membergroup",
            name="group_ptr",
            field=models.OneToOneField(to="auth.Group", on_delete=models.CASCADE)
        ),
        migrations.AddField(
            model_name="membergroupmembership",
            name="membergroup",
            field=models.ForeignKey(to="activemembers.MemberGroup", on_delete=models.CASCADE)
        ),
        migrations.RunPython(migrate_to_authgroups),
        migrations.RemoveField(
            model_name="membergroupmembership",
            name="group",
        ),
        migrations.RenameField(
            model_name="membergroupmembership",
            old_name="membergroup",
            new_name="group",
        ),
    ]
