# Generated by Django 4.2.7 on 2023-11-08 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activemembers", "0044_alter_membergroup_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membergroup",
            options={
                "ordering": ["name"],
                "verbose_name": "member group",
                "verbose_name_plural": "member groups",
            },
        ),
    ]
