# Generated by Django 4.2.7 on 2023-11-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activemembers", "0045_alter_membergroup_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membergroup",
            name="display_members",
            field=models.BooleanField(
                default=False,
                help_text="With this enabled, the members of this committee will be visible to anyone without logging in. Logged-in users can always view the list of members.",
            ),
        ),
    ]
