# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='since',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Hide this announcement before this time.', verbose_name='Display since'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='until',
            field=models.DateTimeField(blank=True, help_text='Hide this announcement after this time.', null=True, verbose_name='Display until'),
        ),
    ]
