# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 17:25
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20170402_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content_en',
            field=tinymce.models.HTMLField(help_text='The content of the announcement; what text to display.', max_length=500, verbose_name='Content (EN)'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content_nl',
            field=tinymce.models.HTMLField(help_text='The content of the announcement; what text to display.', max_length=500, verbose_name='Content (NL)'),
        ),
    ]
