# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20170517_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontpageArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField(default=django.utils.timezone.now, help_text='Hide this article before this time.', verbose_name='Display since')),
                ('until', models.DateTimeField(blank=True, help_text='Hide this article after this time.', null=True, verbose_name='Display until')),
                ('title_en', models.CharField(help_text='The title of the article; what goes in the header', max_length=80, verbose_name='Title (EN)')),
                ('title_nl', models.CharField(help_text='The title of the article; what goes in the header', max_length=80, verbose_name='Title (NL)')),
                ('content_en', tinymce.models.HTMLField(help_text='The content of the article; what text to display.', max_length=5000, verbose_name='Content (EN)')),
                ('content_nl', tinymce.models.HTMLField(help_text='The content of the article; what text to display.', max_length=5000, verbose_name='Content (NL)')),
            ],
            options={
                'ordering': ('-since',),
            },
        ),
    ]
