# Generated by Django 2.2.1 on 2019-11-06 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='since',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Hide this slide before this time.', verbose_name='Display since'),
        ),
    ]
