# Generated by Django 2.2.1 on 2019-11-20 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_auto_20191106_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='since',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text="Hide this slide before this time. When all date- andtime-fields are left blank, the slide won't be visible. It will, however, be visible on an event-pageif it's linked to an event.", null=True, verbose_name='Display since'),
        ),
    ]
