# Generated by Django 3.1.1 on 2020-09-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_auto_20191120_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='content_nl',
        ),
        migrations.RemoveField(
            model_name='frontpagearticle',
            name='content_nl',
        ),
        migrations.RemoveField(
            model_name='frontpagearticle',
            name='title_nl',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='content_nl',
        ),
    ]
