# Generated by Django 3.1.1 on 2020-09-09 18:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0010_auto_20200907_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='content_en',
            new_name='content'
        ),
        migrations.RenameField(
            model_name='frontpagearticle',
            old_name='content_en',
            new_name='content'
        ),
        migrations.RenameField(
            model_name='frontpagearticle',
            old_name='title_en',
            new_name='title'
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='content_en',
            new_name='content'
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=tinymce.models.HTMLField(help_text='The content of the announcement; what text to display.',
                                           max_length=500, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='frontpagearticle',
            name='content',
            field=tinymce.models.HTMLField(help_text='The content of the article; what text to display.',
                                           max_length=5000, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='frontpagearticle',
            name='title',
            field=models.CharField(help_text='The title of the article; what goes in the header', max_length=80,
                                   verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.ImageField(help_text='The content of the slide; what image to display.',
                                    upload_to='public/announcements/slides/', verbose_name='Content'),
        ),
    ]
