# Generated by Django 4.0.4 on 2022-05-27 07:44
import os

import announcements.models
from django.db import migrations, models
import thaliawebsite.storage.backend


def forwards_func(apps, schema_editor):
    Slide = apps.get_model('announcements', 'Slide')

    existing_images = []

    for item in Slide.objects.filter(content__isnull=False):
        item.content.name = item.content.name[7:]
        existing_images.append(item.content.name)
        item.save()

    # This deletes unused images from the filesystem
    storage = item.content.storage
    files = set(storage.listdir("announcements/slides")[1])
    existing_images = set(map(lambda x: os.path.basename(x), existing_images))
    for file in files.difference(existing_images):
        storage.delete(f"announcements/slides/{file}")


def reverse_func(apps, schema_editor):
    Slide = apps.get_model('announcements', 'Slide')

    for item in Slide.objects.filter(content__isnull=False):
        item.photo.name = f"public/{item.content.name}"
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0012_auto_20201209_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.FileField(help_text='The content of the slide; what image to display.', storage=thaliawebsite.storage.backend.get_public_storage, upload_to='announcements/slides/', validators=[announcements.models.validate_image], verbose_name='Content'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
