# Generated by Django 4.1.7 on 2023-03-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0015_remove_slide_linked_event_slide_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="slide",
            old_name="url",
            new_name="custom_url",
        ),
        migrations.AlterField(
            model_name="slide",
            name="custom_url",
            field=models.URLField(
                blank=True,
                help_text="Place the user is taken to when clicking the slide. If left blank, will default to the linked event, if any.",
                null=True,
                verbose_name="Link",
            ),
        ),
    ]
