# Generated by Django 4.2.5 on 2023-10-25 11:13

import announcements.models
from django.db import migrations, models
import functools
import thaliawebsite.storage.backend
import utils.media.services


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0016_rename_url_slide_custom_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slide",
            name="content",
            field=models.FileField(
                help_text="The content of the slide; what image to display.",
                storage=thaliawebsite.storage.backend.get_public_storage,
                upload_to=functools.partial(
                    utils.media.services._generic_upload_to,
                    *(),
                    **{"prefix": "announcements/slides", "token_bytes": 8}
                ),
                validators=[announcements.models.validate_image],
                verbose_name="Content",
            ),
        ),
    ]
