# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-31 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('committees', '0004_auto_20160727_2253'),
        ('members', '0003_merge_20160727_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=254)),
                ('prefix', models.CharField(max_length=200)),
                ('archived', models.BooleanField(default=True)),
                ('moderated', models.BooleanField(default=False)),
                ('committees', models.ManyToManyField(blank=True, to='committees.Committee')),
                ('members', models.ManyToManyField(blank=True, to='members.Member')),
            ],
        ),
        migrations.CreateModel(
            name='VerbatimAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
                ('mailinglist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='mailinglists.MailingList')),
            ],
        ),
        migrations.AddField(
            model_name='listalias',
            name='mailinglist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliasses', to='mailinglists.MailingList'),
        ),
    ]
