# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listalias',
            name='alias',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
