# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-05 20:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglists', '0004_auto_20160805_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listalias',
            name='alias',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Enter a simpler name', regex='^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Enter a simpler name', regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
