# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 17:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglists', '0005_auto_20160805_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listalias',
            name='alias',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Enter a simpler name', regex='^[a-zA-Z0-9]+$')], verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='listalias',
            name='mailinglist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliasses', to='mailinglists.MailingList', verbose_name='Mailing list'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='archived',
            field=models.BooleanField(default=True, verbose_name='Archived'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='committees',
            field=models.ManyToManyField(blank=True, to='activemembers.Committee', verbose_name='Committees'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='members',
            field=models.ManyToManyField(blank=True, to='members.Member', verbose_name='Members'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='moderated',
            field=models.BooleanField(default=False, verbose_name='Moderated'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Enter a simpler name', regex='^[a-zA-Z0-9]+$')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='prefix',
            field=models.CharField(max_length=200, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='verbatimaddress',
            name='address',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='verbatimaddress',
            name='mailinglist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='mailinglists.MailingList', verbose_name='Mailing list'),
        ),
    ]
