# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglists', '0007_auto_20170412_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='prefix',
            field=models.CharField(blank=True, help_text='Enter a prefix that should be prefixed to subjects of all emails sent via this mailinglist.', max_length=200, verbose_name='Prefix'),
        ),
    ]
