# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglists', '0009_auto_20170429_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='members_old',
            field=models.ManyToManyField(blank=True, help_text='Select individual members to include in the list.', to='members.Member', related_name='members_old'),
        ),
    ]
