# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 10:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglists', '0010_1_user_foreign_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglist',
            name='members',
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Select individual members to include in the list.', to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
    ]
