# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_create_proxy_member'),
        ('mailinglists', '0010_4_user_foreign_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Select individual members to include in the list.', to='members.Member', verbose_name='Members'),
        ),
    ]
