# Generated by Django 2.0.2 on 2018-02-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglists', '0011_auto_20171013_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='autoresponse_enabled',
            field=models.BooleanField(default=False, help_text='Indicate whether emails will get an automatic response.', verbose_name='Automatic response enabled'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='autoresponse_text',
            field=models.TextField(blank=True, null=True, verbose_name='Autoresponse text'),
        ),
    ]
