# Generated by Django 2.2.6 on 2019-10-30 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglists', '0015_auto_20191013_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='name',
            field=models.CharField(help_text='Enter the name for the list (i.e. name@thalia.nu).', max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a simpler name', regex='^[a-zA-Z0-9-]+$')], verbose_name='Name'),
        ),
    ]
