# Generated by Django 3.2 on 2021-04-21 16:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import payments.models
import sales.models.order
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0015_auto_20201017_1354'),
        ('activemembers', '0040_remove_multilang_field'),
        ('members', '0039_remove_profile_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='discount')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['created_at'],
                'permissions': [('custom_prices', 'Can use custom prices and discounts in orders')],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('age_restricted', models.BooleanField(default=False, verbose_name='age restricted')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'product list',
                'verbose_name_plural': 'product lists',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('end', models.DateTimeField(help_text='The end time is only indicative and does not prevent orders being created after the shift has ended. This only happens after locking the shift.', verbose_name='end')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('locked', models.BooleanField(default=False, help_text='Prevent orders being changed or created for this shift. This will also clean up all unpaid orders in this shift.', verbose_name='locked')),
                ('managers', models.ManyToManyField(related_name='manager_shifts', to='activemembers.MemberGroup', verbose_name='managers')),
                ('product_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.productlist', verbose_name='product list')),
            ],
            options={
                'permissions': [('override_manager', 'Can access all shifts as manager')],
            },
        ),
        migrations.CreateModel(
            name='ProductListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product', verbose_name='product')),
                ('product_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='sales.productlist', verbose_name='product list')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.AddField(
            model_name='productlist',
            name='products',
            field=models.ManyToManyField(through='sales.ProductListItem', to='sales.Product', verbose_name='products'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, help_text='Only when overriding the default', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='total')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='amount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='sales.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.productlistitem', verbose_name='product')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='sales.OrderItem', to='sales.ProductListItem', verbose_name='items'),
        ),
        migrations.AddField(
            model_name='order',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order', to='members.member', verbose_name='payer'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order', to='payments.payment', verbose_name='payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(default=sales.models.order.default_order_shift, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.shift', verbose_name='shift'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='sales_order_order_i_db59cc_idx'),
        ),
    ]
