# Generated by Django 3.1.3 on 2020-11-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='products',
            field=models.ManyToManyField(related_name='items', through='sales.ProductListItem', to='sales.Product'),
        ),
    ]
