# Generated by Django 3.2.4 on 2021-06-27 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfOrderPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('end', models.DateTimeField(help_text='After this moment, users cannot place orders themselves anymore in this shift.', verbose_name='end')),
                ('product_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.productlist')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.shift')),
            ],
            options={
                'verbose_name': 'self-order period',
                'verbose_name_plural': 'self-order periods',
                'ordering': ['start'],
            },
        ),
    ]
