# Generated by Django 4.0.2 on 2022-02-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_alter_payment_paid_by'),
        ('sales', '0002_auto_20211216_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order', to='payments.payment', verbose_name='payment'),
        ),
    ]
