# Generated by Django 4.0.3 on 2022-04-06 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0040_remove_profile_auto_renew'),
        ('payments', '0019_alter_payment_paid_by'),
        ('sales', '0002_auto_20211216_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_created', to='members.member', verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='payments.payment', verbose_name='payment'),
        ),
        migrations.CreateModel(
            name='SelfOrderPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('end', models.DateTimeField(help_text='After this moment, users cannot place orders themselves anymore in this shift.', verbose_name='end')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.shift')),
            ],
            options={
                'verbose_name': 'self-order period',
                'verbose_name_plural': 'self-order periods',
                'ordering': ['start'],
            },
        ),
    ]
