# Generated by Django 4.0.2 on 2022-02-24 15:58

from django.db import migrations, models
import django.db.models.deletion


def set_product_name(apps, schema_editor):
    """On this migration, set the product name field for all order items to the current name of the product."""
    OrderItem = apps.get_model('sales', 'OrderItem')
    for item in OrderItem.objects.all():
        item.product_name = item.product.product.name
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20211216_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.productlistitem', verbose_name='product'),
        ),
        migrations.RunPython(set_product_name),
    ]
