# Generated by Django 4.0.2 on 2022-04-06 18:25

from django.db import migrations, models
import django.db.models.deletion

def populate_product_name(apps, schema_editor):
    OrderItem = apps.get_model('sales', 'orderitem')
    db_alias = schema_editor.connection.alias
    items = list(OrderItem.objects.using(db_alias).all())
    for item in items:
        item.product_name = item.product.product.name
    OrderItem.objects.using(db_alias).bulk_update(items, ['product_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.productlistitem', verbose_name='product'),
        ),
        migrations.RunPython(populate_product_name)
    ]
