# Generated by Django 4.0.2 on 2022-04-06 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_orderitem_product_name_alter_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfOrderPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('end', models.DateTimeField(help_text='After this moment, users cannot place orders themselves anymore in this shift.', verbose_name='end')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.shift')),
            ],
            options={
                'verbose_name': 'self-order period',
                'verbose_name_plural': 'self-order periods',
                'ordering': ['start'],
            },
        ),
    ]
