# Generated by Django 4.0.7 on 2022-10-05 19:14

from django.db import migrations, models
import payments.models


def set_is_free_and_total_amount_fields(apps, schema_editor):
    """Sets the fields."""
    Order = apps.get_model('sales', 'Order')
    for o in Order.objects.all():
        o._total_amount = sum(o.order_items.values_list('total', flat=True)) - (o.discount or 0)
        o._is_free = o._total_amount == 0
        o.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_order_created_by_selforderperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='_is_free',
            field=models.BooleanField(default=False, verbose_name='is free'),
        ),
        migrations.AddField(
            model_name='order',
            name='_total_amount',
            field=payments.models.PaymentAmountField(decimal_places=2, default=0, max_digits=8, validators=[payments.models.validate_not_zero], verbose_name='total amount'),
            preserve_default=False,
        ),
        migrations.RunPython(set_is_free_and_total_amount_fields, migrations.RunPython.noop),
    ]
