# Generated by Django 3.1.3 on 2020-11-30 22:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20201130_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only when overriding the default', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
