# Generated by Django 3.1.3 on 2020-12-01 09:31

from django.db import migrations, models
import django.db.models.deletion
import sales.models.order


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20201130_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(default=sales.models.order.default_order_shift, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.shift'),
        ),
    ]
