# Generated by Django 4.2.5 on 2023-10-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0006_order_is_free_order_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="productlistitem",
            name="priority",
            field=models.IntegerField(default=1, verbose_name="priority"),
        ),
    ]
