# Generated by Django 5.1.5 on 2025-03-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_alter_productlistitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="selforder",
            field=models.BooleanField(
                default=False,
                help_text="Allow users to order products for themselves for this shift.",
                verbose_name="self-order",
            ),
        ),
    ]
