# Generated by Django 5.1.5 on 2025-05-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_productlistitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_selforder',
            field=models.BooleanField(default=False, help_text='Indicates whether this shift allows self-ordering by members.', verbose_name='is self-order'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end',
            field=models.DateTimeField(help_text='The end time is only indicative and does not prevent orders being created after the shift has ended. This only happens after locking the shift. For self-order shifts, the end time applies to self-ordering, but changes can still be made by managers.', verbose_name='end'),
        ),
        migrations.DeleteModel(
            name='SelfOrderPeriod',
        ),
    ]
