# Generated by Django 5.2.7 on 2025-11-19 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0051_membership_study_long_until'),
        ('sales', '0007_alter_productlistitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order', to='members.member', verbose_name='payer'),
        ),
    ]
