# Generated by Django 5.1.5 on 2025-05-11 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_shift_selforder"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SelfOrderPeriod",
        ),
    ]
