# Generated by Django 5.1.5 on 2025-05-11 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0072_remove_event_shift"),
        ("sales", "0009_delete_selforderperiod"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="linked event",
            ),
        ),
    ]
