# Generated by Django 5.2.8 on 2026-01-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_order_payer'),
        ('sales', '0010_shift_event'),
    ]

    operations = [
    ]
