# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Dutch')], default='nl', max_length=2, verbose_name='language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='active',
            field=models.BooleanField(default=True, help_text='Inactive devices will not be sent notifications', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='device',
            name='registration_id',
            field=models.TextField(verbose_name='registration token'),
        ),
    ]
