# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotifications', '0002_auto_20171103_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('pizza', 'Pizza'), ('event', 'Events'), ('newsletter', 'Newsletter'), ('sponsor', 'Sponsored messages'), ('photo', "Photo's"), ('board', 'Board')], default='general', max_length=10),
        ),
    ]
