# Generated by Django 2.0.2 on 2018-02-28 18:42

from django.db import migrations, models
import pushnotifications.models


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotifications', '0005_populate_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='body_nl',
        ),
        migrations.AlterField(
            model_name='message',
            name='body_nl',
            field=models.TextField(default='', verbose_name='body (NL)'),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='message',
            old_name='title',
            new_name='title_nl',
        ),
        migrations.AlterField(
            model_name='message',
            name='title_nl',
            field=models.CharField(default='', max_length=150,
                                   verbose_name='title (NL)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='body_en',
            field=models.TextField(default='', verbose_name='body (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='title_en',
            field=models.CharField(default='', max_length=150,
                                   verbose_name='title (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='receive_category',
            field=models.ManyToManyField(
                default=pushnotifications.models.default_receive_category,
                to='pushnotifications.Category'
            ),
        ),
    ]
