# Generated by Django 2.0.2 on 2018-03-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotifications', '0006_auto_20180228_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Dutch')], default='en', max_length=2, verbose_name='language'),
        ),
    ]
