# Generated by Django 2.0.2 on 2018-06-13 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotifications', '0007_auto_20180307_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pushnotifications.Message')),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.DateTimeField()),
            ],
            bases=('pushnotifications.message',),
        ),
    ]
