# Generated by Django 2.1.3 on 2018-11-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotifications', '0012_add_descriptions_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='task_id',
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='executed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='scheduled',
            field=models.BooleanField(default=True),
        ),
    ]
