# Generated by Django 2.2 on 2019-06-26 18:06

from django.db import migrations


def forwards_func(apps, schema_editor):
    category = apps.get_model("pushnotifications", "Category")
    db_alias = schema_editor.connection.alias

    cat = category.objects.using(db_alias).get(key='event')
    cat.description_nl = ("Notificaties gerelateerd aan het registreren van "
                          "evenementen en evenementen in het algemeen")
    cat.save()


def reverse_func(apps, schema_editor):
    category = apps.get_model("pushnotifications", "Category")
    db_alias = schema_editor.connection.alias

    cat = category.objects.using(db_alias).get(key='event')
    cat.description_nl = ("Notificaties gerelateerd aan het registreren van "
                          "evenementen en evenementen in het algemeneen")
    cat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('pushnotifications', '0013_auto_20181111_1319'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
