# Generated by Django 2.2.1 on 2019-10-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotifications', '0014_fix_typo'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tmp_sent',
            field=models.DateTimeField(null=True, verbose_name='sent')
        ),
    ]
