# Generated by Django 2.2.1 on 2019-10-16 17:51

from django.db import migrations, models
from django.utils import timezone


def forwards_func(apps, schema_editor):
    message = apps.get_model('pushnotifications', 'Message')
    scheduled = apps.get_model('pushnotifications', 'ScheduledMessage')
    db_alias = schema_editor.connection.alias

    try:
        latest_pk = message.objects.using(db_alias).latest('pk').pk
    except message.DoesNotExist:
        latest_pk = 1
    start_date = timezone.now() - timezone.timedelta(days=latest_pk + 1)

    for m in message.objects.using(db_alias):
        if m.sent:
            m.tmp_sent = start_date + timezone.timedelta(m.pk)
            m.save()

    for m in scheduled.objects.using(db_alias):
        if m.sent:
            m.tmp_sent = m.time
            m.save()


def reverse_func(apps, schema_editor):
    message = apps.get_model('pushnotifications', 'Message')
    db_alias = schema_editor.connection.alias

    for m in message.objects.using(db_alias):
        if m.tmp_sent:
            m.sent = True
            m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotifications', '0014_fix_typo'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tmp_sent',
            field=models.DateTimeField(null=True, verbose_name='sent')
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name='message',
            name='sent',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='tmp_sent',
            new_name='sent',
        ),
    ]
