# Generated by Django 3.2.6 on 2021-08-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotifications', '0018_auto_20200907_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description_en',
            new_name='description'
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_en',
            new_name='name'
        ),
        migrations.RenameField(
            model_name='message',
            old_name='body_en',
            new_name='body'
        ),
        migrations.RenameField(
            model_name='message',
            old_name='title_en',
            new_name='title'
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=150, verbose_name='title'),
        ),
    ]
