# Generated by Django 4.0.3 on 2022-04-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotifications', '0019_remove_multilang_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='registration_id',
            field=models.TextField(unique=True, verbose_name='registration token'),
        ),
    ]
