# Generated by Django 4.1.4 on 2023-02-03 13:06

from django.db import migrations, models, IntegrityError
import django.db.models.deletion

import itertools


def populate_new_album_message(apps, schema_editor):
    """Populate the new NewAlbumMessage based on the old Album.new_album_notification"""
    Album = apps.get_model("photos", "Album")
    NewAlbumMessage = apps.get_model("pushnotifications", "NewAlbumMessage")

    albums = list(
        Album.objects.filter(
            new_album_notification__isnull=False,
        ).select_related("new_album_notification"),
    )

    # Ensure that only one NewAlbumMessage
    # is made for each old ScheduledMessage.
    messages = set()
    for album in albums:
        if album.new_album_notification.pk in messages:
            continue

        messages.add(album.new_album_notification.pk)
        NewAlbumMessage(
            album=album,
            scheduledmessage_ptr=album.new_album_notification,
        ).save_base(raw=True)


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0011_album_new_album_notification"),
        ("pushnotifications", "0020_alter_device_registration_id"),
    ]

    run_before = [
        ("photos", "0019_remove_album_new_album_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewAlbumMessage",
            fields=[
                (
                    "scheduledmessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pushnotifications.scheduledmessage",
                    ),
                ),
                (
                    "album",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp_new_album_notification",
                        to="photos.album",
                    ),
                ),
            ],
            bases=("pushnotifications.scheduledmessage",),
        ),
        migrations.RunPython(
            populate_new_album_message, migrations.RunPython.noop, elidable=True
        ),
    ]
