# Generated by Django 4.1.7 on 2023-03-15 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pizzas", "0018_remove_foodevent_end_reminder"),
        ("photos", "0019_remove_album_new_album_notification"),
        ("events", "0065_remove_event_registration_reminder_and_more"),
        ("pushnotifications", "0020_alter_device_registration_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationReminderMessage",
            fields=[
                (
                    "scheduledmessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pushnotifications.scheduledmessage",
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_reminder",
                        to="events.event",
                    ),
                ),
            ],
            bases=("pushnotifications.scheduledmessage",),
        ),
        migrations.CreateModel(
            name="NewAlbumMessage",
            fields=[
                (
                    "scheduledmessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pushnotifications.scheduledmessage",
                    ),
                ),
                (
                    "album",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_album_notification",
                        to="photos.album",
                    ),
                ),
            ],
            bases=("pushnotifications.scheduledmessage",),
        ),
        migrations.CreateModel(
            name="FoodOrderReminderMessage",
            fields=[
                (
                    "scheduledmessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pushnotifications.scheduledmessage",
                    ),
                ),
                (
                    "food_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="end_reminder",
                        to="pizzas.foodevent",
                    ),
                ),
            ],
            bases=("pushnotifications.scheduledmessage",),
        ),
        migrations.CreateModel(
            name="EventStartReminderMessage",
            fields=[
                (
                    "scheduledmessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pushnotifications.scheduledmessage",
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="start_reminder",
                        to="events.event",
                    ),
                ),
            ],
            bases=("pushnotifications.scheduledmessage",),
        ),
    ]
