# Generated by Django 4.1.4 on 2023-02-03 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0019_remove_album_new_album_notification"),
        ("pushnotifications", "0021_newalbummessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newalbummessage",
            name="album",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="new_album_notification",
                to="photos.album",
            ),
        ),
    ]
