# Generated by Django 4.2 on 2023-04-23 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "pushnotifications",
            "0021_registrationremindermessage_newalbummessage_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="language",
        ),
    ]
