# Generated by Django 4.1.6 on 2023-02-03 22:47

from django.db import migrations, models
import django.db.models.deletion


def populate_food_order_reminder_message(apps, schema_editor):
    FoodEvent = apps.get_model("pizzas", "FoodEvent")
    FoodOrderReminderMessage = apps.get_model(
        "pushnotifications", "FoodOrderReminderMessage"
    )

    for food_event in FoodEvent.objects.filter(
        end_reminder__isnull=False
    ).select_related("end_reminder"):
        FoodOrderReminderMessage(
            food_event=food_event,
            scheduledmessage_ptr=food_event.end_reminder,
        ).save_base(raw=True)


class Migration(migrations.Migration):

    dependencies = [
        ("pizzas", "0014_auto_20210509_1311"),
        ("pushnotifications", "0022_alter_newalbummessage_album"),
    ]

    run_before = [
        ("pizzas", "0018_remove_foodevent_end_reminder"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodOrderReminderMessage",
            fields=[
                (
                    "scheduledmessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pushnotifications.scheduledmessage",
                    ),
                ),
                (
                    "food_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp_end_reminder",
                        to="pizzas.foodevent",
                    ),
                ),
            ],
            bases=("pushnotifications.scheduledmessage",),
        ),
        migrations.RunPython(
            populate_food_order_reminder_message,
            migrations.RunPython.noop,
            elidable=True,
        ),
    ]
