# Generated by Django 4.1.6 on 2023-02-03 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pizzas", "0018_remove_foodevent_end_reminder"),
        ("pushnotifications", "0023_foodorderremindermessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodorderremindermessage",
            name="food_event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="end_reminder",
                to="pizzas.foodevent",
            ),
        ),
    ]
