# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 18:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_main_partner', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('link', models.CharField(blank=True, max_length=255, validators=[django.core.validators.URLValidator()])),
                ('company_profile', models.TextField(blank=True, max_length=3072)),
                ('logo', models.ImageField(upload_to='public/partners/logos/')),
                ('site_header', models.ImageField(blank=True, null=True, upload_to='public/partners/headers/')),
                ('address', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Enter a valid address', regex='^([1-9][e][\\s])*([ëéÉËa-zA-Z]+(([\\.][\\s])|([\\s]))?)+[1-9][0-9]*(([-][1-9][0-9]*)|([\\s]?[ëéÉËa-zA-Z]+))?$')])),
                ('zip_code', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Enter a valid zip code', regex='^[1-9][0-9]{3}[\\s]?[A-Za-z]{2}$')])),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='public/partners/images/')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='partners.Partner')),
            ],
        ),
    ]
