# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name_en', models.CharField(max_length=30, verbose_name='name (EN)')),
                ('name_nl', models.CharField(max_length=30, verbose_name='name (NL)')),
            ],
            options={
                'verbose_name_plural': 'Vanancy Categories',
            },
        ),
    ]
