# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 08:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_vacancycategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=3072)),
                ('link', models.CharField(blank=True, max_length=255, validators=[django.core.validators.URLValidator()])),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='public/partners/vacancy-logos/')),
                ('categories', models.ManyToManyField(blank=True, to='partners.VacancyCategory')),
                ('partner', models.ForeignKey(blank=True, help_text='When you use a partner, the company name and logo below will not be used.', null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.Partner')),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
            },
        ),
    ]
