# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 11:20
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='company_profile',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
