# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_add_tinymce_to_vacancy_and_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='start time')),
                ('end', models.DateTimeField(verbose_name='end time')),
                ('url', models.URLField(verbose_name='website')),
                ('published', models.BooleanField(default=False, verbose_name='published')),
                ('location_en', models.CharField(max_length=255, verbose_name='location (EN)')),
                ('location_nl', models.CharField(max_length=255, verbose_name='location (NL)')),
                ('title_en', models.CharField(max_length=100, verbose_name='title (EN)')),
                ('title_nl', models.CharField(max_length=100, verbose_name='title (NL)')),
                ('description_en', models.TextField(verbose_name='description (EN)')),
                ('description_nl', models.TextField(verbose_name='description (NL)')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='partners.Partner')),
            ],
        ),
    ]
