# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_partnerevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancycategory',
            options={'verbose_name_plural': 'Vacancy Categories'},
        ),
    ]
