# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 20:44
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20161202_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='remarks',
            field=tinymce.models.HTMLField(blank=True, help_text='not shown on the page'),
        ),
    ]
