# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_vacancy_remarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('name',)},
        ),
    ]
