# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_auto_20170120_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
