# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_vacancy_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='expiration_mail_sent',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
