# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_vacancy_expiration_mail_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='expiration_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
