# Generated by Django 2.0.8 on 2018-11-07 19:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0012_auto_20180112_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
