# Generated by Django 2.2.1 on 2019-08-03 16:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0014_partner_is_local_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='expiration_mail_sent',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='partnerevent',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='partners.Partner', verbose_name='partner'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='public/partners/vacancy-logos/', verbose_name='company logo'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='link',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.URLValidator()], verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='When you use a partner, the company name and logo below will not be used.', null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.Partner', verbose_name='partner'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
