# Generated by Django 3.1.2 on 2020-11-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0017_auto_20200907_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Second address line'),
        ),
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.CharField(choices=[('AX', 'Åland Islands'), ('AL', 'Albania'), ('AD', 'Andorra'), ('AT', 'Austria'), ('BY', 'Belarus'), ('BE', 'Belgium'), ('BA', 'Bosnia and Herzegovina'), ('BG', 'Bulgaria'), ('HR', 'Croatia'), ('CZ', 'Czechia'), ('DK', 'Denmark'), ('EE', 'Estonia'), ('FO', 'Faroe Islands'), ('FI', 'Finland'), ('FR', 'France'), ('DE', 'Germany'), ('GI', 'Gibraltar'), ('GR', 'Greece'), ('GG', 'Guernsey'), ('VA', 'Vatican City'), ('HU', 'Hungary'), ('IS', 'Iceland'), ('IE', 'Ireland'), ('IM', 'Isle of Man'), ('IT', 'Italy'), ('JE', 'Jersey'), ('LV', 'Latvia'), ('LI', 'Liechtenstein'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('MK', 'Macedonia (FYROM)'), ('MT', 'Malta'), ('MD', 'Moldova'), ('MC', 'Monaco'), ('ME', 'Montenegro'), ('NL', 'Netherlands'), ('NO', 'Norway'), ('PL', 'Poland'), ('PT', 'Portugal'), ('RO', 'Romania'), ('RU', 'Russian Federation'), ('SM', 'San Marino'), ('RS', 'Serbia'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('ES', 'Spain'), ('SJ', 'Svalbard and Jan Mayen'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('UA', 'Ukraine'), ('GB', 'United Kingdom')], max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='zip_code',
            field=models.CharField(max_length=12),
        ),
    ]
