# Generated by Django 3.2.5 on 2021-08-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0018_auto_20201123_2047'),
    ]

    operations = [
        migrations.RenameField(model_name='partnerevent', old_name='description_en', new_name='description'),
        migrations.RenameField(model_name='partnerevent', old_name='title_en', new_name='title'),
        migrations.RenameField(model_name='partnerevent', old_name='location_en', new_name='location'),
        migrations.RenameField(model_name='vacancycategory', old_name='name_en', new_name='name'),
        migrations.AlterField(
            model_name='partnerevent',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='partnerevent',
            name='location',
            field=models.CharField(max_length=255, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='partnerevent',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='vacancycategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
