# Generated by Django 3.2.7 on 2021-10-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0019_remove_multilang_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='vacancycategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
