# Generated by Django 3.2.7 on 2021-09-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0019_remove_multilang_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='keywords',
            field=models.TextField(default='', verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='location',
            field=models.CharField(default='', max_length=255, verbose_name='location'),
        ),
    ]
