# Generated by Django 3.2.7 on 2021-10-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0021_vacancycategory_subscriptions'),
    ]

    operations = [
        # First make sure all existing models have mail_sent set to True
        migrations.AddField(
            model_name='vacancy',
            name='mail_sent',
            field=models.BooleanField(default=True),
        ),
        # Now set the default for new models to False
        migrations.AlterField(
            model_name='vacancy',
            name='mail_sent',
            field=models.BooleanField(default=False)
        )
    ]
