# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 08:31
from __future__ import unicode_literals

from django.db import migrations


def forward_func(apps, schema_editor):
    ExternalEvent = apps.get_model('events', 'ExternalEvent')
    PartnerEvent = apps.get_model('partners', 'PartnerEvent')

    for event in PartnerEvent.objects.all():
        ExternalEvent.objects.create(
            organiser=event.other_partner or event.partner.name,
            title=event.title,
            description=event.description,
        location= event.location,
            start = event.start,
            end = event.end,
            url=event.url,
            published=event.published,

        )

def backward_func(apps, schema_editor):
    ExternalEvent = apps.get_model('events', 'ExternalEvent')
    PartnerEvent = apps.get_model('partners', 'PartnerEvent')

    for event in ExternalEvent.objects.all():
        PartnerEvent.objects.create(
            other_partner=event.organiser,
            title=event.title,
            description=event.description,
            location=event.location,
            start=event.start,
            end=event.end,
            url=event.url,
            published=event.published,
            category='other'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0021_auto_20211101_2005'),
    ]

    operations = [
        migrations.RunPython(
            forward_func, backward_func
        ),
    ]
