# Generated by Django 4.0.7 on 2022-09-21 19:25

from django.db import migrations, models
import thaliawebsite.storage.backend


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0025_migrate_public_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='alternate_logo',
            field=models.ImageField(blank=True, storage=thaliawebsite.storage.backend.get_public_storage, upload_to='partners/logos/'),
        ),
    ]
