# Generated by Django 4.0.7 on 2022-10-05 18:11

from django.db import migrations, models
from django.core.files.storage import storages


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0025_migrate_public_folders"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="alternate_logo",
            field=models.ImageField(
                blank=True,
                help_text="If set, this logo will be shown on the frontpage banner. Please use files with proper transparency.",
                null=True,
                storage=storages["public"],
                upload_to="partners/logos/",
            ),
        ),
    ]
