# Generated by Django 4.1.6 on 2023-02-08 19:37

from django.db import migrations
import thumbnails.fields


def create_thumbnail_sources(apps, _):
    Source = apps.get_model("thumbnails", "Source")
    Partner = apps.get_model("partners", "Partner")
    for p in Partner.objects.all():
        Source.objects.get_or_create(name=p.logo.name)
        Source.objects.get_or_create(name=p.alternate_logo.name)
        Source.objects.get_or_create(name=p.site_header.name)

    PartnerImage = apps.get_model("partners", "PartnerImage")
    for p in PartnerImage.objects.all():
        Source.objects.get_or_create(name=p.image.name)

    Vacancy = apps.get_model("partners", "Vacancy")
    for v in Vacancy.objects.all():
        Source.objects.get_or_create(name=v.company_logo.name)


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0026_partner_alternate_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="alternate_logo",
            field=thumbnails.fields.ImageField(
                blank=True,
                help_text="If set, this logo will be shown on the frontpage banner. Please use files with proper transparency.",
                null=True,
                upload_to="partners/logos/",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="logo",
            field=thumbnails.fields.ImageField(upload_to="partners/logos/"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="site_header",
            field=thumbnails.fields.ImageField(
                blank=True, null=True, upload_to="partners/headers/"
            ),
        ),
        migrations.AlterField(
            model_name="partnerimage",
            name="image",
            field=thumbnails.fields.ImageField(upload_to="partners/images/"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="company_logo",
            field=thumbnails.fields.ImageField(
                blank=True,
                null=True,
                upload_to="partners/vacancy-logos/",
                verbose_name="company logo",
            ),
        ),
        migrations.RunPython(create_thumbnail_sources, migrations.RunPython.noop)
    ]
