# Generated by Django 4.2.5 on 2023-10-25 11:13

from django.db import migrations
import functools
import thumbnails.fields
import utils.media.services


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0027_alter_partner_alternate_logo_alter_partner_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="alternate_logo",
            field=thumbnails.fields.ImageField(
                blank=True,
                help_text="If set, this logo will be shown on the frontpage banner. Please use files with proper transparency.",
                null=True,
                upload_to=functools.partial(
                    utils.media.services._generic_upload_to,
                    *(),
                    **{"prefix": "partners/logos/", "token_bytes": 8}
                ),
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="logo",
            field=thumbnails.fields.ImageField(
                upload_to=functools.partial(
                    utils.media.services._generic_upload_to,
                    *(),
                    **{"prefix": "partners/logos/", "token_bytes": 8}
                )
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="site_header",
            field=thumbnails.fields.ImageField(
                blank=True,
                null=True,
                upload_to=functools.partial(
                    utils.media.services._generic_upload_to,
                    *(),
                    **{"prefix": "partners/headers/", "token_bytes": 8}
                ),
            ),
        ),
    ]
