# Generated by Django 5.0.2 on 2024-05-22 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0028_alter_partner_alternate_logo_alter_partner_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="address",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid address",
                        regex="^([^/@:;%_]+) \\d+([^/@:;%_]*)",
                    )
                ],
            ),
        ),
    ]
