# Generated by Django 4.2.1 on 2023-10-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FunctionalPermissions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("email_sender", "Send emails using the email sender"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
