# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 18:15
from __future__ import unicode_literals

from django.db import migrations


def insert_sites(apps, schema_editor):
    """Populate the sites model"""
    Site = apps.get_model('sites', 'Site')

    Site.objects.create(domain='thalia.nu', name='thalia')


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_sites)
    ]
