from django.utils.translation import gettext_lazy as _

EUROPE = (
    ("AX", _("Åland Islands")),
    ("AL", _("Albania")),
    ("AD", _("Andorra")),
    ("AT", _("Austria")),
    ("BY", _("Belarus")),
    ("BE", _("Belgium")),
    ("BA", _("Bosnia and Herzegovina")),
    ("BG", _("Bulgaria")),
    ("HR", _("Croatia")),
    ("CZ", _("Czechia")),
    ("DK", _("Denmark")),
    ("EE", _("Estonia")),
    ("FO", _("Faroe Islands")),
    ("FI", _("Finland")),
    ("FR", _("France")),
    ("DE", _("Germany")),
    ("GI", _("Gibraltar")),
    ("GR", _("Greece")),
    ("GG", _("Guernsey")),
    ("VA", _("Vatican City")),
    ("HU", _("Hungary")),
    ("IS", _("Iceland")),
    ("IE", _("Ireland")),
    ("IM", _("Isle of Man")),
    ("IT", _("Italy")),
    ("JE", _("Jersey")),
    ("LV", _("Latvia")),
    ("LI", _("Liechtenstein")),
    ("LT", _("Lithuania")),
    ("LU", _("Luxembourg")),
    ("MK", _("Macedonia (FYROM)")),
    ("MT", _("Malta")),
    ("MD", _("Moldova")),
    ("MC", _("Monaco")),
    ("ME", _("Montenegro")),
    ("NL", _("Netherlands")),
    ("NO", _("Norway")),
    ("PL", _("Poland")),
    ("PT", _("Portugal")),
    ("RO", _("Romania")),
    ("RU", _("Russian Federation")),
    ("SM", _("San Marino")),
    ("RS", _("Serbia")),
    ("SK", _("Slovakia")),
    ("SI", _("Slovenia")),
    ("ES", _("Spain")),
    ("SJ", _("Svalbard and Jan Mayen")),
    ("SE", _("Sweden")),
    ("CH", _("Switzerland")),
    ("UA", _("Ukraine")),
    ("GB", _("United Kingdom")),
)
