# Generated by Django 3.1.1 on 2020-09-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0003_auto_20160916_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandiseitem',
            name='description_nl',
        ),
        migrations.RemoveField(
            model_name='merchandiseitem',
            name='name_nl',
        ),
    ]
