# Generated by Django 3.2.6 on 2021-08-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0004_auto_20200907_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchandiseitem',
            old_name='description_en',
            new_name='description'
        ),
        migrations.RenameField(
            model_name='merchandiseitem',
            old_name='name_en',
            new_name='name'
        ),
        migrations.AlterField(
            model_name='merchandiseitem',
            name='description',
            field=models.TextField()
        ),
        migrations.AlterField(
            model_name='merchandiseitem',
            name='name',
            field=models.CharField(max_length=200)
        ),
    ]
