# Generated by Django 4.0.4 on 2022-05-27 07:44
import os.path

from django.db import migrations, models

import thaliawebsite.storage.backend


def forwards_func(apps, schema_editor):
    MerchandiseItem = apps.get_model('merchandise', 'MerchandiseItem')

    existing_images = []

    for item in MerchandiseItem.objects.filter(image__isnull=False):
        item.image.name = item.image.name[7:]
        existing_images.append(item.image.name)
        item.save()

    # This deletes unused images from the filesystem
    storage = MerchandiseItem().image.storage
    if storage.exists("merchandise"):
        files = set(storage.listdir("merchandise")[1])
        existing_images = set(map(lambda x: os.path.basename(x), existing_images))
        for file in files.difference(existing_images):
            storage.delete(f"merchandise/{file}")


def reverse_func(apps, schema_editor):
    MerchandiseItem = apps.get_model('merchandise', 'MerchandiseItem')

    for item in MerchandiseItem.objects.filter(image__isnull=False):
        item.image.name = f"public/{item.image.name}"
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0007_alter_merchandiseitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandiseitem',
            name='image',
            field=models.ImageField(storage=thaliawebsite.storage.backend.get_public_storage, upload_to='merchandise'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
