# Generated by Django 4.1.6 on 2023-02-22 18:48

from django.db import migrations
import thumbnails.fields


def create_thumbnail_sources(apps, _):
    Source = apps.get_model("thumbnails", "Source")
    MerchandiseItem = apps.get_model("merchandise", "MerchandiseItem")
    for m in MerchandiseItem.objects.all():
        Source.objects.get_or_create(name=m.image.name)


class Migration(migrations.Migration):

    dependencies = [
        ("thumbnails", "0001_initial"),
        ("merchandise", "0009_alter_merchandiseitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchandiseitem",
            name="image",
            field=thumbnails.fields.ImageField(upload_to="merchandise"),
        ),
        migrations.RunPython(create_thumbnail_sources, migrations.RunPython.noop)
    ]
