# Generated by Django 4.1.6 on 2023-02-22 18:48

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ("merchandise", "0009_alter_merchandiseitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchandiseitem",
            name="image",
            field=thumbnails.fields.ImageField(upload_to="merchandise"),
        ),
    ]
