# Generated by Django 4.2.6 on 2023-10-18 13:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import payments.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0047_remove_profile_receive_magazine"),
        ("payments", "0024_alter_payment_paid_by"),
        ("merchandise", "0010_alter_merchandiseitem_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchandiseSale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cash_payment", "Cash payment"),
                            ("card_payment", "Card payment"),
                            ("tpay_payment", "Thalia Pay payment"),
                            ("wire_payment", "Wire payment"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "total_amount",
                    payments.models.PaymentAmountField(
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[payments.models.validate_not_zero],
                        verbose_name="total amount",
                    ),
                ),
                (
                    "total_purchase_amount",
                    payments.models.PaymentAmountField(
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[payments.models.validate_not_zero],
                        verbose_name="total purchase amount",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="notes"),
                ),
            ],
            options={
                "verbose_name": "merchandise sale",
                "verbose_name_plural": "merchandise sales",
            },
        ),
        migrations.AddField(
            model_name="merchandiseitem",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name="MerchandiseSaleItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveSmallIntegerField(
                        default=1, null=True, verbose_name="amount"
                    ),
                ),
                (
                    "total",
                    payments.models.PaymentAmountField(
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[payments.models.validate_not_zero],
                        verbose_name="total",
                    ),
                ),
                (
                    "purchase_total",
                    payments.models.PaymentAmountField(
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[payments.models.validate_not_zero],
                        verbose_name="purchase total",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_merchandise_sale_item_set",
                        to="merchandise.merchandiseitem",
                        verbose_name="item",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_items",
                        to="merchandise.merchandisesale",
                        verbose_name="sale",
                    ),
                ),
            ],
            options={
                "verbose_name": "sale item",
                "verbose_name_plural": "sale items",
            },
        ),
        migrations.AddField(
            model_name="merchandisesale",
            name="items",
            field=models.ManyToManyField(
                through="merchandise.MerchandiseSaleItem",
                to="merchandise.merchandiseitem",
                verbose_name="items",
            ),
        ),
        migrations.AddField(
            model_name="merchandisesale",
            name="paid_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merchandise_sale_set",
                to="members.member",
                verbose_name="paid by",
            ),
        ),
        migrations.AddField(
            model_name="merchandisesale",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merchandise_sale_set",
                to="payments.payment",
                verbose_name="payment",
            ),
        ),
    ]
