# Generated by Django 4.2.6 on 2023-10-26 14:52

from django.db import migrations, models
import django.db.models.deletion


itemlist = []

class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0007_alter_productlistitem_options_and_more"),
        ("merchandise", "0010_alter_merchandiseitem_image"),
    ]

    def store_and_delete_merchandiseitems(apps, schema_editor):
        MerchandiseItem = apps.get_model("merchandise", "MerchandiseItem")
        itemlist = list(MerchandiseItem.objects.all())
        MerchandiseItem.objects.all().delete()

    def create_merchandiseitems(apps, schema_editor):
        MerchandiseItem = apps.get_model("merchandise", "MerchandiseItem")
        for item in itemlist:
            MerchandiseItem.objects.create(
                price=item.price,
                description=item.description,
                image=item.image,
                purchase_price=item.purchase_price,
            )

    operations = [
        migrations.RunPython(store_and_delete_merchandiseitems),
        migrations.RemoveField(
            model_name="merchandiseitem",
            name="id",
        ),
        migrations.RemoveField(
            model_name="merchandiseitem",
            name="name",
        ),
        migrations.AddField(
            model_name="merchandiseitem",
            name="product_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="sales.product",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(create_merchandiseitems),
        migrations.AddField(
            model_name="merchandiseitem",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
