# Generated by Django 4.2.6 on 2023-11-12 21:51

from django.db import migrations, models
import django.db.models.deletion
import payments.models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0007_alter_productlistitem_options_and_more"),
        ("merchandise", "0011_alter_merchandiseitem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchandiseitem",
            name="price",
            field=payments.models.PaymentAmountField(
                decimal_places=2,
                help_text="Current sales price of the merchandise item per piece (incl. VAT).",
                max_digits=8,
                validators=[payments.models.validate_not_zero],
            ),
        ),
        migrations.CreateModel(
            name="MerchandiseProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sales.product",
                    ),
                ),
                (
                    "stock_value",
                    payments.models.PaymentAmountField(
                        decimal_places=2,
                        help_text="Current stock ledger value of this product per piece (excl. VAT).",
                        max_digits=8,
                        validators=[payments.models.validate_not_zero],
                    ),
                ),
                (
                    "merchandise_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchandise.merchandiseitem",
                    ),
                ),
            ],
            bases=("sales.product",),
        ),
    ]
