# Generated by Django 4.2.6 on 2023-10-26 14:52

from django.db import migrations, models
import django.db.models.deletion


itemlist = []


def store_and_delete_merchandiseitems(apps, schema_editor):
    MerchandiseItem = apps.get_model("merchandise", "MerchandiseItem")
    global itemlist
    itemlist = list(MerchandiseItem.objects.all())
    MerchandiseItem.objects.all().delete()


# This does not seem to work yet
def create_merchandiseitems(apps, schema_editor):
    MerchandiseItem = apps.get_model("merchandise", "MerchandiseItem")
    Product = apps.get_model("sales", "Product")

    for item in itemlist:
        product = Product.objects.create(
            name=item.name,
        )

        MerchandiseItem.objects.create(
            product_ptr=product,
            price=item.price,
            description=item.description,
            image=item.image,
            stock_value=0,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0007_alter_productlistitem_options_and_more"),
        ("merchandise", "0011_alter_merchandiseitem_image"),
    ]

    operations = [
        migrations.RunPython(store_and_delete_merchandiseitems),
        migrations.RemoveField(
            model_name="merchandiseitem",
            name="id",
        ),
        migrations.RemoveField(
            model_name="merchandiseitem",
            name="name",
        ),
        migrations.AddField(
            model_name="merchandiseitem",
            name="product_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="sales.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="merchandiseitem",
            name="stock_value",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.RunPython(create_merchandiseitems),
    ]
