from django.conf import settings


def get(key, default):
    return getattr(settings, key, default)


MONEYBIRD_ADMINISTRATION_ID = get("MONEYBIRD_ADMINISTRATION_ID", None)
MONEYBIRD_API_TOKEN = get("MONEYBIRD_API_TOKEN", None)

MONEYBIRD_RESOURCE_TYPES = get("MONEYBIRD_RESOURCE_TYPES", [])

MONEYBIRD_WEBHOOK_SITE_DOMAIN = get(
    "MONEYBIRD_WEBHOOK_SITE_DOMAIN", "http://localhost:8000"
)
MONEYBIRD_WEBHOOK_EVENTS = get("MONEYBIRD_WEBHOOK_EVENTS", [])
MONEYBIRD_WEBHOOK_ID = get("MONEYBIRD_WEBHOOK_ID", None)
MONEYBIRD_WEBHOOK_TOKEN = get("MONEYBIRD_WEBHOOK_TOKEN", None)
MONEYBIRD_WEBHOOK_ALLOW_INSECURE = get("MONEYBIRD_WEBHOOK_ALLOW_INSECURE", False)

MONEYBIRD_AUTO_PUSH = get("MONEYBIRD_AUTO_PUSH", True)
MONEYBIRD_FETCH_BEFORE_PUSH = get("MONEYBIRD_FETCH_BEFORE_PUSH", False)
