# Generated by Django 3.1.6 on 2021-02-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='This is what you use after the root domain.', max_length=32, unique=True, verbose_name='name for the url')),
                ('url', models.URLField(help_text='The url the user will be redirected to.', verbose_name='redirection target')),
                ('immediate', models.BooleanField(default=False, help_text='Make sure to only do this when users expect an immediate redirect, if they expect a Thalia site a redirect will be confusing.', verbose_name='redirect without information page')),
            ],
        ),
    ]
