#!/bin/sh

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
	branch=$(basename $remote_ref)
	if [[ $branch = "master" ]] ; then
		read -p "You are going to push to master, are you sure? [yN] " -n 1 -r < /dev/tty
		echo
		if [[ ! $REPLY =~ ^[Yy]$ ]]; then
			echo "Not pushing."
			exit 1
		fi
	fi
done

exit 0
