# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='This date is used to extract the week of this newsletter, best scenario:always use the monday of the week the newsletter is for. If you leave it empty no week is shown.', null=True, verbose_name='Date')),
                ('sent', models.BooleanField(default=False)),
                ('title_en', models.CharField(help_text='The title is used for the email subject.', max_length=150, verbose_name='Title (EN)')),
                ('title_nl', models.CharField(help_text='The title is used for the email subject.', max_length=150, verbose_name='Title (NL)')),
                ('description_en', tinymce.models.HTMLField(help_text='This is the text that starts the newsletter. It always begins with "Dear members" and you can append whatever you want.', verbose_name='Introduction (EN)')),
                ('description_nl', tinymce.models.HTMLField(help_text='This is the text that starts the newsletter. It always begins with "Dear members" and you can append whatever you want.', verbose_name='Introduction (NL)')),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=150, verbose_name='Title (EN)')),
                ('title_nl', models.CharField(max_length=150, verbose_name='Title (NL)')),
                ('description_en', tinymce.models.HTMLField(verbose_name='Description (EN)')),
                ('description_nl', tinymce.models.HTMLField(verbose_name='Description (NL)')),
                ('start_datetime', models.DateTimeField(verbose_name='Start date and time')),
                ('end_datetime', models.DateTimeField(verbose_name='End date and time')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Price (in Euro)')),
                ('penalty_costs', models.DecimalField(decimal_places=2, default=0, help_text='This is the price that a member has to pay when he/she did not show up.', max_digits=5, verbose_name='Costs (in Euro)')),
                ('where_en', models.CharField(max_length=150, verbose_name='Where (EN)')),
                ('where_nl', models.CharField(max_length=150, verbose_name='Where (NL)')),
                ('what_en', models.CharField(max_length=150, verbose_name='What (EN)')),
                ('what_nl', models.CharField(max_length=150, verbose_name='What (NL)')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletters.Newsletter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsletterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=150, verbose_name='Title (EN)')),
                ('title_nl', models.CharField(max_length=150, verbose_name='Title (NL)')),
                ('description_en', tinymce.models.HTMLField(verbose_name='Description (EN)')),
                ('description_nl', tinymce.models.HTMLField(verbose_name='Description (NL)')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletters.Newsletter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
