# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_auto_20161109_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterevent',
            name='show_costs_warning',
            field=models.BooleanField(default=True, verbose_name='Show warnings about costs'),
        ),
    ]
