# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_auto_20161109_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': (('send_newsletter', 'Can send newsletter'),)},
        ),
    ]
