# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0004_newsletterevent_show_costs_warning'),
        ('newsletters', '0004_auto_20161211_2145'),
    ]

    operations = [
    ]
