# Generated by Django 2.1.7 on 2019-04-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0006_make_newslettercontent_non_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Send date'),
        ),
    ]
