# Generated by Django 2.1.8 on 2019-04-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0007_newsletter_send_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettercontent',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='newslettercontent',
            name='order',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='order'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='newslettercontent',
            order_with_respect_to=None,
        ),
    ]
