# Generated by Django 2.2.1 on 2019-11-03 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0008_auto_20190413_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletterevent',
            name='what_en',
        ),
        migrations.RemoveField(
            model_name='newsletterevent',
            name='what_nl',
        ),
    ]
