# Generated by Django 3.1.1 on 2020-09-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0010_newslettercontent_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='description_nl',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='title_nl',
        ),
        migrations.RemoveField(
            model_name='newslettercontent',
            name='description_nl',
        ),
        migrations.RemoveField(
            model_name='newslettercontent',
            name='title_nl',
        ),
        migrations.RemoveField(
            model_name='newsletterevent',
            name='where_nl',
        ),
    ]
