# Generated by Django 3.2.6 on 2021-08-10 20:25

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0011_auto_20200907_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='description_en',
            new_name='description'
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='title_en',
            new_name='title'
        ),
        migrations.RenameField(
            model_name='newslettercontent',
            old_name='description_en',
            new_name='description'
        ),
        migrations.RenameField(
            model_name='newslettercontent',
            old_name='title_en',
            new_name='title'
        ),
        migrations.RenameField(
            model_name='newsletterevent',
            old_name='where_en',
            new_name='where'
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='description',
            field=tinymce.models.HTMLField(help_text='This is the text that starts the newsletter. It always begins with "Dear members" and you can append whatever you want.', verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='title',
            field=models.CharField(help_text='The title is used for the email subject.', max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='newslettercontent',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='newslettercontent',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='newsletterevent',
            name='where',
            field=models.CharField(max_length=150, verbose_name='Where'),
        ),
    ]
