# Generated by Django 4.1.3 on 2023-01-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletters", "0001_squashed_0015_embed_images_html"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletterevent",
            name="penalty_costs",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="This is the price that a member has to pay when he/she did not show up.",
                max_digits=8,
                null=True,
                verbose_name="Costs (in Euro)",
            ),
        ),
        migrations.AlterField(
            model_name="newsletterevent",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                max_digits=8,
                null=True,
                verbose_name="Price (in Euro)",
            ),
        ),
    ]
