# Generated by Django 4.2 on 2023-04-18 12:25

import os
from django.db import migrations, models
import newsletters.models
from django.core.files.storage import DefaultStorage


def populate_rendered_file(apps, schema_editor):
    Newsletter = apps.get_model("newsletters", "Newsletter")

    storage = DefaultStorage()
    for newsletter in Newsletter.objects.all():
        file_path = os.path.join("newsletters", f"{newsletter.pk}_en.html")
        if storage.exists(file_path):
            file = storage.open(file_path, "rb")
            newsletter.rendered_file = file
            newsletter.save()
            file.close()


class Migration(migrations.Migration):
    dependencies = [
        ("newsletters", "0016_alter_newsletterevent_penalty_costs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="rendered_file",
            field=models.FileField(
                null=True, upload_to=newsletters.models.newsletter_filename
            ),
        ),
        migrations.RunPython(populate_rendered_file, migrations.RunPython.noop),
    ]
