# Generated by Django 2.0.1 on 2018-02-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_delete_becomeamemberdocument'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='old_entry', to='registrations.Entry'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='membership',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_membership', to='members.Membership'),
        ),
        migrations.AddField(
            model_name='entry',
            name='membership',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Membership'),
        ),
        migrations.AddField(
            model_name='entry',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations_entry', to='registrations.Payment'),
        ),
    ]
