# Generated by Django 2.0.1 on 2018-02-03 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('registrations', '0003_migrate_payment_fields_to_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='membership',
        ),
    ]
