# Generated by Django 2.0.1 on 20180203 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('registrations', '0004_remove_payment_fields'),
    ]

    database_operations = [
        migrations.AlterModelTable('Payment', 'payments_payment')
    ]

    state_operations = [
        migrations.DeleteModel('Payment')
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='payment',
            field=models.UUIDField(
                blank=True, null=True
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        ),
    ]
