# Generated by Django 2.0.1 on 2018-02-03 13:27

from django.db import migrations


def forwards_func(apps, schema_editor):
    Entry = apps.get_model('registrations', 'entry')
    db_alias = schema_editor.connection.alias
    for entry in Entry.objects.using(db_alias).all():
        payment = entry.payment
        if payment and payment.processed and entry.status == 'accepted':
            entry.status = 'completed'
            entry.save()


def reverse_func(apps, schema_editor):
    Entry = apps.get_model('registrations', 'entry')
    db_alias = schema_editor.connection.alias
    for entry in Entry.objects.using(db_alias).all():
        payment = entry.payment
        if payment and payment.processed and entry.status == 'completed':
            entry.status = 'accepted'
            entry.save()


class Migration(migrations.Migration):
    dependencies = [
        ('registrations', '0006_restore_payment_field_and_add_completed_status'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
