# Generated by Django 2.0.2 on 2018-07-04 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_change_registration_status_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='please enter a valid phone number', regex='^\\+?\\d+$')], verbose_name='phone number'),
        ),
    ]
