# Generated by Django 2.0.2 on 2018-07-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_auto_20180704_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='optin_birthday',
            field=models.BooleanField(default=False, verbose_name='birthday calendar opt-in'),
        ),
        migrations.AddField(
            model_name='registration',
            name='optin_mailinglist',
            field=models.BooleanField(default=False, verbose_name='mailinglist opt-in'),
        ),
    ]
