# Generated by Django 2.0.8 on 2018-08-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_auto_20180704_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'registration', 'verbose_name_plural': 'registrations'},
        ),
    ]
