# Generated by Django 2.0.8 on 2018-09-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_auto_20180828_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='membership_type',
            field=models.CharField(choices=[('member', 'Member'), ('supporter', 'Benefactor')], default='member', max_length=40, verbose_name='membership type'),
        ),
    ]
