# Generated by Django 2.0.9 on 2018-10-31 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('registrations', '0012_auto_20181024_2004'), ('registrations', '0013_auto_20181031_1911')]

    dependencies = [
        ('registrations', '0011_auto_20180928_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='address_street',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='please use the format <street> <number>', regex='^.+ \\d+.*')], verbose_name='street and house number'),
        ),
    ]
