# Generated by Django 2.0.8 on 2018-11-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_auto_20181024_2004_squashed_0013_auto_20181031_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='length',
            field=models.CharField(choices=[('year', 'One year -- €7.50'), ('study', 'Until graduation -- €30.00')], max_length=20, verbose_name='membership length'),
        ),
    ]
