# Generated by Django 2.0.8 on 2018-11-28 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_auto_20181114_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='student_number',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='enter a valid student- or e/z/u-number.', regex='([Ss]\\d{7}|[EZUezu]\\d{6,7})')], verbose_name='student number'),
        ),
    ]
