# Generated by Django 2.1.3 on 2018-11-26 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0014_fill_new_payments_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations_entry', to='payments.Payment'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student_number',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='enter a valid student- or e/z/u-number.', regex='([Ss]\\d{7}|[EZUezu]\\d{6,7})')], verbose_name='student number'),
        ),
    ]
