# Generated by Django 2.1.5 on 2019-01-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0017_benefactor_model_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='membership_type',
            field=models.CharField(choices=[('member', 'Member'), ('benefactor', 'Benefactor')], default='member', max_length=40, verbose_name='membership type'),
        ),
    ]
