# Generated by Django 2.2 on 2019-04-25 09:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_benefactor_model_value'),
        ('registrations', '0018_benefactor_model_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='contribution',
            field=models.FloatField(blank=True, default=7.5, null=True, validators=[django.core.validators.MinValueValidator(7.5)], verbose_name='contribution'),
        ),
        migrations.AddField(
            model_name='entry',
            name='no_references',
            field=models.BooleanField(default=False, verbose_name='no references required'),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.Entry', verbose_name='entry')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member', verbose_name='member')),
            ],
            options={
                'unique_together': {('member', 'entry')},
            },
        ),
    ]
