# Generated by Django 2.2.1 on 2019-09-25 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0019_auto_20190425_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='student_number',
            field=models.CharField(blank=True, help_text="With prefix. For example: 's5603249'.", max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='enter a valid student- or e/z/u-number.', regex='([Ss]\\d{7}|[EZUezu]\\d{6,7})')], verbose_name='student number'),
        ),
    ]
