# Generated by Django 2.2.6 on 2019-11-06 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0020_auto_20190925_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(blank=True, help_text='Enter value to override the auto-generated username (e.g. if it is not unique)', max_length=64, null=True, validators=[django.core.validators.RegexValidator(message='Please use 64 characters or fewer. Letters and digits only.', regex='^[a-zA-Z0-9]{1,64}$')], verbose_name='Username'),
        ),
    ]
