# Generated by Django 3.1.1 on 2020-09-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0021_auto_20191106_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='language',
        ),
    ]
