# Generated by Django 3.0.3 on 2020-03-25 19:45

import django.core.validators
from django.db import migrations, models


def set_contribution_fields(apps, schema_editor):
    """On this migration, set the empty contribution fields to the paid contribution."""
    Entry = apps.get_model('registrations', 'Entry')
    for entry in Entry.objects.all():
        if entry.payment and not entry.contribution:
            entry.contribution = entry.payment.amount


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0022_remove_registration_language'),
    ]

    operations = [
        migrations.RunPython(set_contribution_fields)
    ]
