# Generated by Django 3.0.3 on 2020-05-19 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20200510_2042'),
        ('registrations', '0022_auto_20200325_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.BankAccount'),
        ),
    ]
