# Generated by Django 3.0.3 on 2020-03-25 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0023_auto_20200325_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='contribution',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(7.5)], default=7.5, verbose_name='contribution'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations_entry', to='payments.Payment'),
        ),
    ]
