# Generated by Django 3.1.2 on 2020-10-05 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0024_auto_20200325_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='contribution',
            field=models.DecimalField(decimal_places=2, default=7.5, max_digits=5, validators=[django.core.validators.MinValueValidator(7.5)], verbose_name='contribution'),
        ),
    ]
