# Generated by Django 3.1.1 on 2020-09-18 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20200905_1142'),
        ('registrations', '0024_auto_20200325_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.bankaccount'),
        ),
    ]
