# Generated by Django 3.1.6 on 2021-03-15 20:05

from django.db import migrations, models
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0025_auto_20201005_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='bic',
            field=localflavor.generic.models.BICField(blank=True, help_text='This field is optional for Dutch bank accounts.', max_length=11, null=True, verbose_name='BIC'),
        ),
        migrations.AddField(
            model_name='registration',
            name='direct_debit',
            field=models.BooleanField(default=False, help_text='When the registration is accepted and this checkbox is enabled, a Thalia Pay payment will be created for this user and the registration will be completed immediately. This can only be selected if a bank account is added with direct debit authorisation during registration.'),
        ),
        migrations.AddField(
            model_name='registration',
            name='iban',
            field=localflavor.generic.models.IBANField(blank=True, include_countries=('AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GI', 'GR', 'HR', 'HU', 'IE', 'IS', 'IT', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK', 'SM'), max_length=34, null=True, use_nordea_extensions=False, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='registration',
            name='initials',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='initials'),
        ),
        migrations.AddField(
            model_name='registration',
            name='signature',
            field=models.TextField(blank=True, null=True, verbose_name='signature'),
        ),
    ]
