# Generated by Django 3.1.1 on 2020-09-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0025_registration_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='pay_with_tpay',
            field=models.BooleanField(default=False, help_text='If selected, when the registration is accepted, immediately a Thalia Pay payment will be created for this user and the registration will be completed directly. This can only be selected if a bank account is added with direct debit authorization.'),
        ),
    ]
