# Generated by Django 3.2 on 2021-06-07 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_remove_profile_language'),
        ('registrations', '0026_auto_20210315_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membership'),
        ),
    ]
