# Generated by Django 3.2.6 on 2021-08-12 10:27

import django.core.validators
from django.db import migrations, models
import members.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0027_alter_entry_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Who should we contact in case of emergencies', max_length=255, null=True, verbose_name='Emergency contact name'),
        ),
        migrations.AddField(
            model_name='registration',
            name='emergency_contact_phone_number',
            field=models.CharField(blank=True, help_text='The phone number for the emergency contact', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^\\+?\\d+$')], verbose_name='Emergency contact phone number'),
        ),
        migrations.AddField(
            model_name='registration',
            name='photo',
            field=models.ImageField(blank=True, help_text='An optional profile picture that will be shown to other members', null=True, upload_to=members.models.profile._profile_image_path, verbose_name='Photo'),
        ),
    ]
