# Generated by Django 3.2.6 on 2021-08-12 10:47

from django.db import migrations, models
import registrations.models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0028_auto_20210812_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='photo',
            field=models.ImageField(blank=True, help_text='An optional profile picture that will be shown to other members', null=True, upload_to=registrations.models._registration_profile_image_path, verbose_name='Photo'),
        ),
    ]
