# Generated by Django 4.2.2 on 2023-06-21 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0029_alter_registration_iban"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="first_name",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The first name should not contain special characters like '/' or '@'.",
                        regex="^[/@:;%_?\\|]",
                    )
                ],
                verbose_name="First name",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="last_name",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The first name should not contain special characters like '/' or '@'.",
                        regex="^[/@:;%_?\\|]",
                    )
                ],
                verbose_name="Last name",
            ),
        ),
    ]
