# Generated by Django 4.1.7 on 2023-03-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0029_alter_entry_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirm", "Awaiting email confirmation"),
                    ("review", "Ready for review"),
                    ("rejected", "Rejected"),
                    ("accepted", "Accepted"),
                    ("completed", "Completed"),
                ],
                default="confirm",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
