# Generated by Django 4.2.7 on 2023-12-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0030_alter_registration_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="length",
            field=models.CharField(
                choices=[
                    ("year", "One year -- €7.50"),
                    ("study", "Until graduation -- €30.00"),
                ],
                help_text="Warning: changing this in the admin does not update the contribution.",
                max_length=20,
                verbose_name="membership length",
            ),
        ),
    ]
