# Generated by Django 5.0.2 on 2024-03-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0031_alter_entry_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="optin_thabloid",
            field=models.BooleanField(default=True, verbose_name="Thabloid opt-in"),
        ),
    ]
