# Generated by Django 5.0.6 on 2024-06-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0032_registration_optin_thabloid"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="optin_sharing",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")],
                help_text="Do you give permission to post photos that you are on of events on social media?",
                max_length=3,
                null=True,
                verbose_name="Opt-in sharing photos on social media",
            ),
        ),
    ]
