# Generated by Django 5.0.6 on 2024-06-20 15:52

import django.db.models.deletion
from django.db import migrations, models


def forward_func(apps, schema_editor):
    """Move the `payment` relation to both `Registration` and `Renewal` models.

    This should not trigger the "You are trying to unlink a payment from its payable."
    protection, because renaming the Entry.payment field to tmp_payment makes the
    existing payment relation undiscoverable.
    Instead, from the perspective of those signal receivers, we are solely
    linking a not previously linked payment to a registration or renewal.
    """
    Registration = apps.get_model("registrations", "Registration")
    Renewal = apps.get_model("registrations", "Renewal")

    for renewal in Renewal.objects.all():
        renewal.payment = renewal.tmp_payment
        renewal.save()

    for registration in Registration.objects.all():
        registration.payment = registration.tmp_payment
        registration.save()


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0025_alter_payment_processed_by"),
        ("registrations", "0032_registration_optin_thabloid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entry",
            old_name="payment",
            new_name="tmp_payment",
        ),
        migrations.RunPython(forward_func, migrations.RunPython.noop, elidable=True),
        migrations.AddField(
            model_name="registration",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="renewal",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.payment",
            ),
        ),
        migrations.RemoveField(
            model_name="entry",
            name="tmp_payment",
        ),
    ]
