# Generated by Django 5.2.7 on 2025-11-20 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_alter_payment_paid_by'),
        ('registrations', '0033_remove_entry_payment_registration_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.payment'),
        ),
    ]
