# Generated by Django 5.1.2 on 2025-01-19 11:48

import django.core.validators
import django.db.models.deletion
import functools
import localflavor.generic.models
import payments.models
import utils.media.services
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0051_membership_study_long_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', payments.models.PaymentAmountField(decimal_places=2, help_text='How much did you pay (in euros)?', max_digits=8, validators=[payments.models.validate_not_zero])),
                ('iban', localflavor.generic.models.IBANField(help_text='The bank account to which the reimbursement should be sent.', include_countries=('AD', 'AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GI', 'GR', 'HR', 'HU', 'IE', 'IS', 'IT', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK', 'SM', 'VA'), max_length=34, use_nordea_extensions=False, verbose_name='IBAN')),
                ('date_incurred', models.DateField(help_text='When was this payment made?')),
                ('description', models.TextField(help_text='Why did you make this payment?', max_length=512, validators=[django.core.validators.MinLengthValidator(10)])),
                ('receipt', models.FileField(upload_to=functools.partial(utils.media.services._generic_upload_to, *(), **{'prefix': 'reimbursements/receipts', 'token_bytes': 8}))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('verdict', models.CharField(blank=True, choices=[('approved', 'Approved'), ('denied', 'Denied')], max_length=40, null=True)),
                ('verdict_clarification', models.TextField(blank=True, help_text='Why did you choose this verdict?', null=True)),
                ('evaluated_at', models.DateTimeField(editable=False, null=True)),
                ('evaluated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements_approved', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reimbursements', to='members.member')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
