# Generated by Django 5.1.5 on 2025-05-21 17:30

import django.core.validators
import functools
import payments.models
import utils.media.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0002_remove_reimbursement_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='amount',
            field=payments.models.PaymentAmountField(decimal_places=2, help_text='How much did you pay (in euros)?', max_digits=8, validators=[django.core.validators.MinValueValidator(0), payments.models.validate_not_zero]),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='receipt',
            field=models.FileField(upload_to=functools.partial(utils.media.services._generic_upload_to, *(), **{'prefix': 'reimbursements/receipts', 'token_bytes': 8}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'tiff'], message='Only pdf, jpg, jpeg and png files are allowed.')]),
        ),
    ]
