# Generated by Django 5.1.5 on 2025-05-22 12:52

import django.core.validators
import functools
import reimbursements.models
import utils.media.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0003_alter_reimbursement_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='receipt',
            field=models.FileField(upload_to=functools.partial(utils.media.services._generic_upload_to, *(), **{'prefix': 'reimbursements/receipts', 'token_bytes': 8}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'tiff'], message='Only pdf, jpg, jpeg, png and tiff files are allowed.'), reimbursements.models.validate_file_size]),
        ),
    ]
