# Generated by Django 5.1.5 on 2025-05-22 12:17

import payments.models
import utils.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0003_alter_reimbursement_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='amount',
            field=payments.models.PaymentAmountField(decimal_places=2, help_text='How much did you pay (in euros)?', max_digits=8, validators=[utils.validators.RangeValueValidator(lower=0, lower_inclusive=False), payments.models.validate_not_zero]),
        ),
    ]
