# Generated by Django 5.1.5 on 2025-06-25 18:01

import django.core.validators
import functools
import reimbursements.models
import utils.media.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0004_alter_reimbursement_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='receipt',
            field=models.FileField(upload_to=functools.partial(utils.media.services._generic_upload_to, *(), **{'prefix': 'reimbursements/receipts', 'token_bytes': 8}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Only pdf, jpg, jpeg and png files are allowed.'), reimbursements.models.validate_file_size]),
        ),
    ]
