# Generated by Django 5.1.5 on 2025-06-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0004_alter_reimbursement_amount'),
        ('reimbursements', '0005_alter_reimbursement_receipt'),
    ]

    operations = [
    ]
