# Generated by Django 3.2.9 on 2021-12-14 12:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0049_event_optional_registrations'),
        ('members', '0039_remove_profile_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Channel name')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Publish date')),
                ('status', models.CharField(choices=[('0', 'Not started'), ('1', 'Started'), ('2', 'Finished'), ('3', 'Published')], default='0', max_length=40)),
                ('drive_folder', models.CharField(default='', max_length=200)),
                ('assigned_to', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='Assigned to')),
                ('channel', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='promotion.promotionchannel')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
