# Generated by Django 3.2.9 on 2021-12-16 11:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0049_event_optional_registrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Channel name')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField(default=datetime.date.today, verbose_name='Publish date')),
                ('assigned_to', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Assigned to')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('started', 'Started'), ('finished', 'Finished'), ('published', 'Published')], default='not_started', max_length=40, verbose_name='status')),
                ('drive_folder', models.URLField(blank=True, default='', max_length=400, null=True)),
                ('remarks', tinymce.models.HTMLField(verbose_name='remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.promotionchannel', verbose_name='channel')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'Promotion request',
                'verbose_name_plural': 'Promotion requests',
            },
        ),
    ]
