# Generated by Django 3.2.9 on 2021-12-15 10:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_auto_20211215_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionrequest',
            name='remarks',
            field=tinymce.models.HTMLField(verbose_name='remarks'),
        ),
    ]
