# Generated by Django 4.0.7 on 2022-09-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_alter_promotionrequest_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='promotionrequest',
            managers=[
            ],
        ),
    ]
