# Generated by Django 3.2.9 on 2021-12-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_alter_promotionrequest_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionrequest',
            name='assigned_to',
            field=models.CharField(default='', max_length=40, verbose_name='Assigned to'),
        ),
    ]
