# Generated by Django 4.2.5 on 2023-09-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotion", "0003_alter_promotionrequest_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionchannel",
            name="publisher_reminder_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Publisher Reminder Email",
            ),
        ),
    ]
