# Generated by Django 3.2.9 on 2021-12-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_event_optional_registrations'),
        ('promotion', '0004_alter_promotionrequest_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionrequest',
            name='channel',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='promotion.promotionchannel', verbose_name='channel'),
        ),
        migrations.AlterField(
            model_name='promotionrequest',
            name='drive_folder',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='promotionrequest',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='event'),
        ),
    ]
