# Generated by Django 4.2.8 on 2024-01-11 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotion", "0005_promotionrequest_status_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotionrequest",
            name="publish_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Publish date"
            ),
        ),
    ]
