# Generated by Django 5.0.1 on 2024-02-07 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotion", "0006_alter_promotionrequest_publish_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionchannel",
            name="publish_deadline",
            field=models.DurationField(
                default=datetime.timedelta(days=14),
                verbose_name="Minimum time between request and publish",
            ),
        ),
        migrations.AlterField(
            model_name="promotionrequest",
            name="publish_date",
            field=models.DateField(verbose_name="Publish date"),
        ),
    ]
