# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 10:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('events', '0001_initial'), ('events', '0002_auto_20160813_1620'), ('events', '0003_remove_event_registration_required'), ('events', '0004_event_cancel_deadline'), ('events', '0005_auto_20160914_2154'), ('events', '0006_auto_20160928_1919'), ('events', '0006_auto_20160921_2201'), ('events', '0007_merge_20161016_1322'), ('events', '0008_auto_20161016_1704'), ('events', '0007_auto_20161009_2352'), ('events', '0009_merge_20161019_2025'), ('events', '0010_auto_20161019_2221'), ('events', '0011_auto_20161019_2235')]

    initial = True

    dependencies = [
        ('members', '0004_auto_20160805_1435'),
        ('activemembers', '0004_auto_20160727_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanRegistrationInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='last changed')),
                ('value', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('start', models.DateTimeField(verbose_name='start time')),
                ('end', models.DateTimeField(verbose_name='end time')),
                ('registration_start', models.DateTimeField(blank=True, null=True, verbose_name='registration start')),
                ('registration_end', models.DateTimeField(blank=True, null=True, verbose_name='registration end')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('map_location', models.CharField(help_text='Location of Huygens: Heyendaalseweg 135, Nijmegen. Not shown as text!!', max_length=255, verbose_name='location for minimap')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('cost', models.DecimalField(decimal_places=2, default=0, help_text='Actual cost of event.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cost')),
                ('max_participants', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='maximum number of participants')),
                ('registration_required', models.BooleanField(default=False, verbose_name='registration required')),
                ('no_registration_message', models.CharField(blank=True, help_text='Default: No registration required', max_length=200, null=True, verbose_name='message when there is no registration')),
                ('published', models.BooleanField(default=False, verbose_name='published')),
                ('organiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activemembers.Committee')),
            ],
            options={
                'ordering': ('-start',),
            },
        ),
        migrations.CreateModel(
            name='IntegerRegistrationInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='last changed')),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Use this for non-members', max_length=50, null=True, verbose_name='name')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='registration date')),
                ('date_cancelled', models.DateTimeField(blank=True, null=True, verbose_name='cancellation date')),
                ('present', models.BooleanField(default=False, verbose_name='Present')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='RegistrationInformationField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('checkbox', 'checkbox'), ('charfield', 'text field'), ('intfield', 'integer field')], max_length=10, verbose_name='field type')),
                ('name', models.CharField(max_length=100, verbose_name='field name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='TextRegistrationInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='last changed')),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.RegistrationInformationField')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Registration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='integerregistrationinformation',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.RegistrationInformationField'),
        ),
        migrations.AddField(
            model_name='integerregistrationinformation',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Registration'),
        ),
        migrations.AddField(
            model_name='booleanregistrationinformation',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.RegistrationInformationField'),
        ),
        migrations.AddField(
            model_name='booleanregistrationinformation',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Registration'),
        ),
        migrations.AddField(
            model_name='registrationinformationfield',
            name='required',
            field=models.BooleanField(default=True, verbose_name='required'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationinformationfield',
            name='type',
            field=models.CharField(choices=[('boolean', 'Checkbox'), ('text', 'Text'), ('integer', 'Integer')], max_length=10, verbose_name='field type'),
        ),
        migrations.RemoveField(
            model_name='registrationinformationfield',
            name='description',
        ),
        migrations.RemoveField(
            model_name='registrationinformationfield',
            name='name',
        ),
        migrations.AddField(
            model_name='registrationinformationfield',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description (EN)'),
        ),
        migrations.AddField(
            model_name='registrationinformationfield',
            name='description_nl',
            field=models.TextField(blank=True, null=True, verbose_name='description (NL)'),
        ),
        migrations.AddField(
            model_name='registrationinformationfield',
            name='name_en',
            field=models.CharField(default='foo', max_length=100, verbose_name='field name (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationinformationfield',
            name='name_nl',
            field=models.CharField(default='bar', max_length=100, verbose_name='field name (NL)'),
            preserve_default=False,
        ),
        migrations.AlterOrderWithRespectTo(
            name='registrationinformationfield',
            order_with_respect_to='event',
        ),
        migrations.AlterField(
            model_name='registration',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='paid'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='present',
            field=models.BooleanField(default=False, verbose_name='present'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('member', 'event', 'name', 'date_cancelled')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activemembers.Committee'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_required',
        ),
        migrations.AddField(
            model_name='event',
            name='cancel_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cancel deadline'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='no_registration_message',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='location_en',
            field=models.CharField(default='', max_length=255, verbose_name='location (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location_nl',
            field=models.CharField(default='', max_length=255, verbose_name='location (NL)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='no_registration_message_en',
            field=models.CharField(blank=True, help_text='Default: No registration required', max_length=200, null=True, verbose_name='message when there is no registration (EN)'),
        ),
        migrations.AddField(
            model_name='event',
            name='no_registration_message_nl',
            field=models.CharField(blank=True, help_text='Default: No registration required', max_length=200, null=True, verbose_name='message when there is no registration (NL)'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(default='', max_length=100, verbose_name='title (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title_nl',
            field=models.CharField(default='', max_length=100, verbose_name='title (NL)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activemembers.Committee', verbose_name='organiser'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(default='', verbose_name='description (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description_nl',
            field=models.TextField(default='', verbose_name='description (NL)'),
            preserve_default=False,
        ),
    ]
