# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activemembers.Committee'),
        ),
    ]
