# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160813_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registration_required',
        ),
    ]
