# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_registration_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancel_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cancel deadline'),
        ),
    ]
