# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_cancel_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='no_registration_message',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='location_en',
            field=models.CharField(default='', max_length=255, verbose_name='location (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location_nl',
            field=models.CharField(default='', max_length=255, verbose_name='location (NL)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='no_registration_message_en',
            field=models.CharField(blank=True, help_text='Default: No registration required', max_length=200, null=True, verbose_name='message when there is no registration (EN)'),
        ),
        migrations.AddField(
            model_name='event',
            name='no_registration_message_nl',
            field=models.CharField(blank=True, help_text='Default: No registration required', max_length=200, null=True, verbose_name='message when there is no registration (NL)'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(default='', max_length=100, verbose_name='title (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title_nl',
            field=models.CharField(default='', max_length=100, verbose_name='title (NL)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='activemembers.Committee', verbose_name='organiser'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='paid'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='present',
            field=models.BooleanField(default=False, verbose_name='present'),
        ),
    ]
