# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20160914_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(default='', verbose_name='description (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description_nl',
            field=models.TextField(default='', verbose_name='description (NL)'),
            preserve_default=False,
        ),
    ]
