# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20160921_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationinformationfield',
            name='required',
            field=models.BooleanField(default=True, verbose_name='required'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationinformationfield',
            name='type',
            field=models.CharField(choices=[('boolean', 'Checkbox'), ('text', 'Text'), ('integer', 'Integer')], max_length=10, verbose_name='field type'),
        ),
    ]
