# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20160921_2201'),
        ('events', '0006_auto_20160928_1919'),
    ]

    operations = [
    ]
