# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_merge_20161016_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booleanregistrationinformation',
            name='explanation_field',
        ),
        migrations.RemoveField(
            model_name='integerregistrationinformation',
            name='explanation_field',
        ),
        migrations.RemoveField(
            model_name='textregistrationinformation',
            name='explanation_field',
        ),
    ]
