# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 22:29
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20161022_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description_en',
            field=tinymce.models.HTMLField(verbose_name='description (EN)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_nl',
            field=tinymce.models.HTMLField(verbose_name='description (NL)'),
        ),
    ]
