# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20161016_1704'),
        ('events', '0007_auto_20161009_2352'),
    ]

    operations = [
    ]
