# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20161024_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='registration date'),
        ),
    ]
