# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_merge_20161019_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationinformationfield',
            name='description',
        ),
        migrations.RemoveField(
            model_name='registrationinformationfield',
            name='name',
        ),
    ]
