# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20161019_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationinformationfield',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description (EN)'),
        ),
        migrations.AddField(
            model_name='registrationinformationfield',
            name='description_nl',
            field=models.TextField(blank=True, null=True, verbose_name='description (NL)'),
        ),
        migrations.AddField(
            model_name='registrationinformationfield',
            name='name_en',
            field=models.CharField(default='foo', max_length=100, verbose_name='field name (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationinformationfield',
            name='name_nl',
            field=models.CharField(default='bar', max_length=100, verbose_name='field name (NL)'),
            preserve_default=False,
        ),
    ]
