# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20161130_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_end',
            field=models.DateTimeField(blank=True, help_text="If you set a registration period registration will be required. If you don't set one, registration won't be required.", null=True, verbose_name='registration end'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_start',
            field=models.DateTimeField(blank=True, help_text="If you set a registration period registration will be required. If you don't set one, registration won't be required.", null=True, verbose_name='registration start'),
        ),
    ]
