# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20161209_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='map_location',
            field=models.CharField(help_text='Location of Huygens: Heyendaalseweg 135, Nijmegen. Location of Mercator 1: Toernooiveld 212, Nijmegen. Not shown as text!!', max_length=255, verbose_name='location for minimap'),
        ),
    ]
