# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 20:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20161221_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cost',
        ),
        migrations.AddField(
            model_name='event',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fine if participant does not show up (at least €5).', max_digits=5, validators=[django.core.validators.MinValueValidator(5)], verbose_name='fine'),
        ),
    ]
