# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20170405_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('drinks', 'Drinks'), ('activity', 'Activity'), ('lunchlecture', 'Lunch Lecture'), ('generalmeeting', 'General Meeting'), ('workshop', 'Workshop'), ('other', 'Other')], default='other', max_length=40, verbose_name='category'),
        ),
    ]
