# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 18:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fine if participant does not show up (at least €5).', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='fine'),
        ),
    ]
