# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 19:18
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    Registration = apps.get_model('events', 'registration')
    db_alias = schema_editor.connection.alias
    for reg in Registration.objects.using(db_alias).all():
        if reg.paid:
            reg.payment = 'cash_payment'
            reg.save()


def reverse_func(apps, schema_editor):
    Registration = apps.get_model('events', 'registration')
    db_alias = schema_editor.connection.alias
    for reg in Registration.objects.using(db_alias).all():
        if reg.payment != 'no_payment':
            reg.paid = True
            reg.save()


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0018_0_registration_payment'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
