# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20170524_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment',
            field=models.CharField(choices=[('no_payment', 'No payment'), ('cash_payment', 'Paid with cash'), ('card_payment', 'Paid with card')], default='no_payment', max_length=20, verbose_name='payment'),
        )
    ]
