# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_2_registration_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='send_cancel_email',
            field=models.BooleanField(default=False, help_text='Send an email to the organising party when a member cancels their registration after the deadline.', verbose_name='send cancellation notifications'),
        ),
        migrations.AlterField(
            model_name='event',
            name='send_cancel_email',
            field=models.BooleanField(default=True,
                                      help_text='Send an email to the organising party when a member cancels their registration after the deadline.',
                                      verbose_name='send cancellation notifications'),
        ),
    ]
