# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_3_user_foreign_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='member_old',
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('member', 'event', 'name', 'date_cancelled')]),
        ),
    ]
