# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 08:31
from __future__ import unicode_literals

from django.db import migrations


def forward_func(apps, schema_editor):
    Registration = apps.get_model('events', 'Registration')

    for registration in Registration.objects.all():
        if registration.member:
            registration.member_old = registration.member
            registration.save(update_fields=('member_old',))


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_0_user_foreign_keys'),
    ]

    operations = [
        migrations.RunPython(
            code=forward_func,
        ),
    ]
