# Generated by Django 2.0.1 on 2018-01-08 11:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20171129_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='member',
            field=models.ForeignKey(blank=True, limit_choices_to=django.db.models.query_utils.Q(('membership__until__isnull', True), ('membership__until__gt', datetime.date(2018, 1, 8)), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
    ]
