# Generated by Django 2.0.6 on 2018-06-13 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_emailchange'),
        ('events', '0025_auto_20180112_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=32)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
    ]
