# Generated by Django 2.0.2 on 2018-06-13 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotifications', '0008_scheduledmessage'),
        ('events', '0025_auto_20180112_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_event', to='pushnotifications.ScheduledMessage'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_event', to='pushnotifications.ScheduledMessage'),
        ),
    ]
