# Generated by Django 2.0.2 on 2018-06-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20180613_2046'),
        ('events', '0026_feedtoken'),
    ]

    operations = [
    ]
