# Generated by Django 2.0.9 on 2018-11-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_merge_20180618_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('drinks', 'Drinks'), ('activity', 'Activity'), ('lunchlecture', 'Lunch Lecture'), ('generalmeeting', 'General Meeting'), ('workshop', 'Workshop'), ('alumni', 'Alumni'), ('party', 'Party'), ('other', 'Other')], default='other', max_length=40, verbose_name='category'),
        ),
    ]
