# Generated by Django 2.0.8 on 2018-11-14 19:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20181111_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description_en',
            field=tinymce.models.HTMLField(help_text='Please fill in both of the description boxes (EN/NL), even if your event is Dutch only! Fill in the English description in Dutch then.', verbose_name='description (EN)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_nl',
            field=tinymce.models.HTMLField(help_text='Please fill in both of the description boxes (EN/NL), even if your event is Dutch only! Fill in the English description in Dutch then.', verbose_name='description (NL)'),
        ),
    ]
