# Generated by Django 2.0.8 on 2018-11-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auto_20181114_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='no_registration_message_en',
            field=models.CharField(blank=True, help_text='Default: No registration required / Geen aanmelding vereist', max_length=200, null=True, verbose_name='message when there is no registration (EN)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='no_registration_message_nl',
            field=models.CharField(blank=True, help_text='Default: No registration required / Geen aanmelding vereist', max_length=200, null=True, verbose_name='message when there is no registration (NL)'),
        ),
    ]
