# Generated by Django 2.1.3 on 2018-11-26 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20181127_1819'),
        ('events', '0032_event_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='payment',
            new_name='payment_str',
        ),
        migrations.AddField(
            model_name='registration',
            name='payment',
            field=models.OneToOneField(null=True, blank=True,
                                       on_delete=django.db.models.deletion.PROTECT,
                                       related_name='events_registration',
                                       to='payments.Payment'),
        ),
    ]
