# Generated by Django 2.2.1 on 2019-08-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_category_improvement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('alumni', 'Alumni'), ('education', 'Education'), ('career', 'Career'), ('leisure', 'Leisure'), ('association', 'Association Affairs'), ('other', 'Other')], help_text='Alumni: Events organised for alumni, Education: Education focused events, Career: Career focused events, Leisure: borrels, parties, game activities etc., Association Affairs: general meetings or any other board related events, Other: anything else.', max_length=40, verbose_name='category'),
        ),
    ]
