# Generated by Django 2.2.1 on 2019-10-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_auto_20190804_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_start',
            field=models.DateTimeField(blank=True, help_text="If you set a registration period registration will be required. If you don't set one, registration won't be required. Prefer times when people don't have lectures, e.g. 12:30 instead of 13:37.", null=True, verbose_name='registration start'),
        ),
    ]
