# Generated by Django 3.0.2 on 2020-03-29 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_auto_20191120_1906'),
        ('members', '0036_profile_email_gsuite_only'),
        ('payments', '0006_payment_topic'),
        ('events', '0039_event_slide'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='EventRegistration',
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ('date',), 'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
        migrations.AlterField(
            model_name='event',
            name='slide',
            field=models.ForeignKey(blank=True, help_text="Change the header-image on the event's info-page to one specific to this event.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='announcements.Slide', verbose_name='slide'),
        ),
    ]
