# Generated by Django 3.0.6 on 2020-08-02 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20200510_2042'),
        ('events', '0040_auto_20200329_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_registration', to='payments.Payment'),
        ),
    ]
