# Generated by Django 3.1.1 on 2020-09-07 16:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_auto_20200802_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description_nl',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_nl',
        ),
        migrations.RemoveField(
            model_name='event',
            name='no_registration_message_nl',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title_nl',
        ),
        migrations.RemoveField(
            model_name='registrationinformationfield',
            name='description_nl',
        ),
        migrations.RemoveField(
            model_name='registrationinformationfield',
            name='name_nl',
        ),
        migrations.AlterField(
            model_name='event',
            name='description_en',
            field=tinymce.models.HTMLField(verbose_name='description (EN)'),
        ),
    ]
