# Generated by Django 3.1.4 on 2020-12-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_auto_20200907_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='map_location',
            field=models.CharField(help_text="Location of Huygens: Heyendaalseweg 135, Nijmegen. Location of Mercator 1: Toernooiveld 212, Nijmegen. Use the input 'discord' or 'online' for special placeholders. Not shown as text!!", max_length=255, verbose_name='location for minimap'),
        ),
    ]
