# Generated by Django 3.2 on 2021-04-21 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('events', '0045_auto_20210217_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='shift',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.shift'),
        ),
    ]
