# Generated by Django 3.2.2 on 2021-05-14 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('events', '0046_event_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='shift',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.shift'),
        ),
    ]
