# Generated by Django 3.2.4 on 2021-07-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_remove_multilang_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='optional_registrations',
            field=models.BooleanField(default=True, help_text='Participants can indicate their optional presence, even though registration is not actually required. This ignores registration start and end time or cancellation deadlines, optional registration will be enabled directly after publishing until the end of the event.', verbose_name='allow optional registrations'),
        ),
    ]
