# Generated by Django 3.2.9 on 2021-12-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_event_optional_registrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short',
            field=models.TextField(default=0, help_text='A short text of max 500 characters for the front page and the newsletter.', max_length=500, verbose_name='short description'),
            preserve_default=False,
        ),
    ]
