# Generated by Django 3.2.9 on 2021-12-04 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_event_optional_registrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='remarks'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='special price'),
        ),
    ]
