# Generated by Django 3.2.9 on 2021-12-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_event_optional_registrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='caption',
            field=models.TextField(default='N/A', help_text='A short text of max 500 characters for promotion and the newsletter.', max_length=500, verbose_name='caption'),
            preserve_default=False,
        ),
    ]
