# Generated by Django 3.2.10 on 2021-12-16 22:00

import django.core.validators
from django.db import migrations
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_event_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fine',
            field=payments.models.PaymentAmountField(decimal_places=2, default=0, help_text='Fine if participant does not show up (at least €5).', max_digits=8, validators=[django.core.validators.MinValueValidator(0), payments.models.validate_not_zero], verbose_name='fine'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=payments.models.PaymentAmountField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0), payments.models.validate_not_zero], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='special_price',
            field=payments.models.PaymentAmountField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0), payments.models.validate_not_zero], verbose_name='special price'),
        ),
    ]
