# Generated by Django 3.2.10 on 2022-01-12 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_auto_20211216_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for non-members', max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for non-members', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^\\+?\\d+$')], verbose_name='Phone number'),
        ),
    ]
