# Generated by Django 3.2.11 on 2022-01-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_auto_20220112_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventregistration',
            old_name='email',
            new_name='alt_email',
        ),
        migrations.RenameField(
            model_name='eventregistration',
            old_name='phone_number',
            new_name='alt_phone_number',
        ),
    ]
