# Generated by Django 4.0.3 on 2022-04-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_externalevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='no_registration_message',
            field=models.CharField(blank=True, help_text='Default: No registration required. This field accepts HTML tags as well, e.g. links with &lta href="https://example.com" target="_blank"&gthttps://example.com&lt/a&gt', max_length=200, null=True, verbose_name='message when there is no registration'),
        ),
    ]
