# Generated by Django 4.0.3 on 2022-04-15 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_alter_event_no_registration_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationinformationfield',
            name='delete_after',
            field=models.DateField(default=django.utils.timezone.now, help_text='The data entered in this field will automatically be deleted after this date for privacy purposes. Please choose a value, e.g. 1 month after the event.', verbose_name='delete after'),
            preserve_default=False,
        ),
    ]
