# Generated by Django 4.1.3 on 2022-11-16 19:43

from django.db import migrations
import members.models.member


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0041_alter_profile_photo"),
        ("events", "0059_multiple_event_organisers"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventsUser",
            fields=[],
            options={
                "verbose_name": "Events user",
                "verbose_name_plural": "Events users",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("members.member",),
            managers=[
                ("objects", members.models.member.MemberManager()),
                ("current_members", members.models.member.CurrentMemberManager()),
                ("active_members", members.models.member.ActiveMemberManager()),
            ],
        ),
    ]
