# Generated by Django 4.1.2 on 2022-11-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0060_event_registration_msg_cancelled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registration_msg_cancelled_final",
            field=models.CharField(
                blank=True,
                help_text="Default: Your registration for this event is cancelled. Note that you cannot re-register.",
                max_length=200,
                null=True,
                verbose_name="message when user cancelled their registration in time and cannot re-register",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_msg_cancelled",
            field=models.CharField(
                blank=True,
                help_text="Default: Your registration for this event is cancelled. You may still re-register",
                max_length=200,
                null=True,
                verbose_name="message when user cancelled their registration in time",
            ),
        ),
    ]
