# Generated by Django 4.1.3 on 2022-11-16 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import members.models.member


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("members", "0041_alter_profile_photo"),
        ("events", "0060_eventsuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedEventsUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="Reason for blacklisting",
                        null=True,
                        verbose_name="Remarks",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklisted_events_user",
                        to="members.member",
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blacklisted events user",
                "verbose_name_plural": "Blacklisted events users",
            },
            bases=("members.member",),
            managers=[
                ("objects", members.models.member.MemberManager()),
                ("current_members", members.models.member.CurrentMemberManager()),
                ("active_members", members.models.member.ActiveMemberManager()),
            ],
        ),
    ]
