# Generated by Django 4.1.3 on 2022-11-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0061_event_registration_msg_cancelled_final_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="registration_msg_cancelled_late",
            field=models.CharField(
                blank=True,
                help_text="Default: Your registration is cancelled after the deadline and you will pay a fine of €{fine}.",
                max_length=200,
                null=True,
                verbose_name="message when user cancelled their registration late and will pay a fine",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_msg_expired",
            field=models.CharField(
                blank=True,
                help_text="Default: Registration is not possible anymore.",
                max_length=200,
                null=True,
                verbose_name="message when the registration deadline expired and the user is not registered",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_msg_full",
            field=models.CharField(
                blank=True,
                help_text="Default: Registrations are full, but you can join the waiting list.",
                max_length=200,
                null=True,
                verbose_name="message when registrations are open, but full and the user is not registered",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_msg_open",
            field=models.CharField(
                blank=True,
                help_text="Default: You can register now.",
                max_length=200,
                null=True,
                verbose_name="message when registrations are open and the user is not registered",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_msg_optional",
            field=models.CharField(
                blank=True,
                help_text="Default: You can optionally register for this event.",
                max_length=200,
                null=True,
                verbose_name="message when registrations are optional and the user is not registered",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_msg_optional_registered",
            field=models.CharField(
                blank=True,
                help_text="Default: You are optionally registered for this event.",
                max_length=200,
                null=True,
                verbose_name="message when registrations are optional and the user is registered",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_msg_registered",
            field=models.CharField(
                blank=True,
                help_text="Default: You are registered for this event.",
                max_length=200,
                null=True,
                verbose_name="message when user is registered",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_msg_waitinglist",
            field=models.CharField(
                blank=True,
                help_text="Default: You are in queue position {pos}.",
                max_length=200,
                null=True,
                verbose_name="message when user is on the waiting list",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_msg_will_open",
            field=models.CharField(
                blank=True,
                help_text="Default: Registration will open {regstart}.",
                max_length=200,
                null=True,
                verbose_name="message when registrations are still closed (and the user is not registered)",
            ),
        ),
    ]
