# Generated by Django 4.1.3 on 2023-01-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0062_alter_event_registration_msg_cancelled_late_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registration_without_membership",
            field=models.BooleanField(
                default=False,
                help_text="Users without a currently active membership (i.e. past members) are allowed to register for this event. This is useful for events aimed at alumni, for example.",
                verbose_name="registration_without_membership",
            ),
        ),
    ]
