# Generated by Django 4.1.7 on 2023-02-22 20:07

from django.db import migrations, models

def slugText(str):
    return str.replace(" ", "-").lower()

def give_old_events_slugs(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    generated_slugs = []
    for event in Event.objects.all():
        default_slug = slugText(event.title) + "-" + str(event.start.year)
        slug = default_slug
        i = 1
        while slug in generated_slugs:
            slug = default_slug + "-" + str(i)
            i += 1

        event.slug = slug
        event.save()
        generated_slugs.append(slug)



class Migration(migrations.Migration):
    dependencies = [
        ("events", "0063_event_registration_without_membership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(null=True, unique=True, verbose_name="slug"),
        ),
        migrations.RunPython(give_old_events_slugs),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(null=False, unique=True, verbose_name="slug"),
        ),
    ]
