# Generated by Django 4.1.4 on 2023-02-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0063_event_registration_without_membership_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="slide",
        ),
    ]
