# Generated by Django 4.1.7 on 2023-03-01 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0064_event_slug"),
        ("events", "0064_remove_event_slide"),
    ]

    operations = []
