# Generated by Django 4.1.6 on 2023-02-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0064_remove_event_slide"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="registration_reminder",
        ),
        migrations.RemoveField(
            model_name="event",
            name="start_reminder",
        ),
    ]
