# Generated by Django 4.1.7 on 2023-03-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0065_remove_event_registration_reminder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="A short name for the event, used in the URL. For example: thalia-weekend-2023. Note that the slug must be unique.",
                null=True,
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
