# Generated by Django 4.2 on 2023-05-10 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0066_event_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventregistration",
            options={
                "get_latest_by": "pk",
                "ordering": ("date",),
                "verbose_name": "Registration",
                "verbose_name_plural": "Registrations",
            },
        ),
    ]
