# Generated by Django 4.2.1 on 2023-05-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0066_event_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="show_map_location",
            field=models.BooleanField(
                default=True, verbose_name="show url for location"
            ),
        ),
    ]
