# Generated by Django 5.0.2 on 2024-05-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0069_alter_event_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="update_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for participants to update their registration. Updating is always allowed until registration closes, so this field can only be used to extend this.",
                null=True,
                verbose_name="registration update deadline",
            ),
        ),
    ]
