# Generated by Django 4.2.5 on 2023-11-01 16:40

from django.db import migrations

def distribute_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")

    view_unpublished_permission = Permission.objects.get(content_type__app_label="events", codename="view_unpublished")
    view_event_permission = Permission.objects.get(content_type__app_label="events", codename="view_event")

    MemberGroup = apps.get_model("activemembers", "MemberGroup")

    for group in MemberGroup.objects.filter(permissions=view_event_permission):
        group.permissions.add(view_unpublished_permission)

    for group in MemberGroup.objects.filter(chair_permissions=view_event_permission):
        group.chair_permissions.add(view_unpublished_permission)



class Migration(migrations.Migration):
    dependencies = [
        ("events", "0069_alter_event_options"),
    ]

    operations = [
        migrations.RunPython(distribute_permissions, migrations.RunPython.noop),
    ]
