# Generated by Django 5.1.5 on 2025-05-11 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0071_alter_textregistrationinformation_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="shift",
        ),
    ]
