# Generated by Django 5.1.5 on 2025-08-13 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0071_alter_textregistrationinformation_value'),
        ('members', '0051_membership_study_long_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member'),
        ),
    ]
