# Generated by Django 5.2.7 on 2025-11-20 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0073_alter_eventregistration_member'),
        ('members', '0051_membership_study_long_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.member'),
        ),
    ]
