# Generated by Django 5.2.8 on 2026-01-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0072_remove_event_shift'),
        ('events', '0074_alter_eventregistration_member'),
    ]

    operations = [
    ]
