---

name: Build Dependencies Docker Image
on:
  schedule:
    - cron: 0 4 * * *
  push:
    branches:
      - master
    paths:
      - poetry.lock

jobs:
  build-docker:
    name: Build Dependencies Docker Image
    runs-on: ubuntu-18.04
    env:
      DOCKER_DEPENDENCIES_LATEST: thalia/concrexit-dependencies:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login --username "thaliawww" --password-stdin

      - name: Build dependencies Docker image
        run:  docker build --file Dockerfile.dependencies --quiet --build-arg "install_dev_requirements=1" --tag "${DOCKER_DEPENDENCIES_LATEST}" .

      - name: Push Docker image
        run: docker push "${DOCKER_DEPENDENCIES_LATEST}"
