name: "Pull Request Labeler"
on:
  - pull_request

jobs:
  pr-type-labeler:
    name: Label based on branch name
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v4
        with:
          configuration-path: .github/type-labeler.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
