---

name: Review Environments

on:
  issue_comment:
    types: [created, edited]

jobs:
  create:
    name: Deploy review environment
    runs-on: ubuntu-18.04
    if: github.event.issue.pull_request && github.event.comment.body == 'deploy review'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get commit hash
        run: echo "COMMIT_SHA=$(curl --location --silent ${{ github.event.issue.pull_request.patch_url }} | grep --perl-regexp '^From [a-z0-9]{40} ' | tail --lines 1 | cut --delimiter " " --fields 2)" >> "${GITHUB_ENV}"

      - name: Generate username
        run: echo "username=$(head /dev/urandom | tr -dc 'a-z' | head -c 10)" >> "${GITHUB_ENV}"

      - name: Generate password
        run: echo "password=$(head /dev/urandom | tr -dc 'a-zA-Z' | head -c 32)" >> "${GITHUB_ENV}"

      - name: Set variables in bootstrap script
        run: >-
          sed --in-place
          --expression "s/@version@/$COMMIT_SHA/g"
          --expression "s/@username@/$username/g"
          --expression "s/@password@/$password/g"
          resources/continuous-integration/review/ec2-bootstrap.sh

      - name: Run script to create review environment
        run: resources/continuous-integration/review/review-host-create.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1

      - uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            The review environment deployment is done. Please wait for the website to come up.
            You can login on [${{ env.COMMIT_SHA }}.public.review.technicie.nl](https://${{ env.COMMIT_SHA }}.public.review.technicie.nl/) with:
            Username: ${{ env.username }}
            Password: ${{ env.password }}

  remove:
    name: Remove review environment
    runs-on: ubuntu-18.04
    if: github.event.issue.pull_request && github.event.comment.body == 'remove review'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get commit hash
        run: echo "COMMIT_SHA=$(curl --location --silent ${{ github.event.issue.pull_request.patch_url }} | grep --perl-regexp '^From [a-z0-9]{40} ' | tail --lines 1 | cut --delimiter " " --fields 2)" >> "${GITHUB_ENV}"

      - name: Run script to remove review environment
        run: resources/continuous-integration/review/review-host-remove.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
