name: 'Update flake.lock'
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 17 * * 3' # Runs every Wednesday afternoon

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Nix
      uses: cachix/install-nix-action@v16
    - run: nix flake update --commit-lock-file
      shell: bash
      env:
        GIT_AUTHOR_NAME: github-actions[bot]
        GIT_AUTHOR_EMAIL: <github-actions[bot]@users.noreply.github.com>
        GIT_COMMITTER_NAME: github-actions[bot]
        GIT_COMMITTER_EMAIL: <github-actions[bot]@users.noreply.github.com>
    - run: |
        content="$(git log --format=%b -n 1)"
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        echo "::set-output name=msg::$content"
      shell: bash
      id: commit_message
    - name: Create PR
      uses: peter-evans/create-pull-request@v3
      id: cpr
      with:
        branch: update_flake_lock_action
        delete-branch: true
        title: "flake.lock: Update"
        token: ${{ secrets.THALIA_SERVICE_PAT }}
        labels: "dependency-update"
        body: |
          Automated changes by the Update Flake.lock GitHub Action.

          ```
          ${{ steps.commit_message.outputs.msg }}
          ```
    - name: Enable Pull Request Automerge
      if: steps.cpr.outputs.pull-request-operation == 'created'
      uses: peter-evans/enable-pull-request-automerge@v2
      with:
        token: ${{ secrets.THALIA_SERVICE_PAT }}
        merge-method: squash
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
