# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='shareable',
            field=models.BooleanField(default=False),
        ),
    ]
