# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20160809_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='rotation',
            field=models.IntegerField(choices=[(0, 0), (90, 90), (180, 180), (270, 270)], default=0, help_text='This does not modify the original image file.'),
        ),
    ]
