# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_album_shareable'),
        ('photos', '0004_auto_20160810_1447'),
    ]

    operations = [
    ]
