# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_merge_20160812_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-date', 'title')},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('file',)},
        ),
    ]
