# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-18 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20170120_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='_cover',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_album', to='photos.Photo', verbose_name='cover image'),
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='album',
            name='dirname',
            field=models.CharField(max_length=200, verbose_name='directory name'),
        ),
        migrations.AlterField(
            model_name='album',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='hidden'),
        ),
        migrations.AlterField(
            model_name='album',
            name='shareable',
            field=models.BooleanField(default=False, verbose_name='shareable'),
        ),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Album', verbose_name='album'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to=photos.models.photo_uploadto, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='hidden'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='rotation',
            field=models.IntegerField(choices=[(0, 0), (90, 90), (180, 180), (270, 270)], default=0, help_text='This does not modify the original image file.', verbose_name='rotation'),
        ),
    ]
