# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 19:01
from __future__ import unicode_literals

from django.db import migrations, models


def add_english_titles(apps, schema_editor):
    Album = apps.get_model('photos', 'Album')
    for album in Album.objects.all():
        album.title_en = album.title_nl
        album.save()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('photos', '0007_auto_20170218_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='title',
            new_name='title_nl',
        ),
        migrations.AlterField(
            model_name='album',
            name='title_nl',
            field=models.CharField(default='', max_length=200, verbose_name='title (NL)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='title_en',
            field=models.CharField(default='', max_length=200, verbose_name='title (EN)'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-date', 'title_en')},
        ),
        migrations.RunPython(
            code=add_english_titles,
        ),
    ]
