# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 18:26
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20170218_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='_digest',
            field=models.CharField(
                default='',
                blank=True,
                max_length=40,
                verbose_name='digest'),
            preserve_default=False,
        ),
    ]
