# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 19:03
from __future__ import unicode_literals
import hashlib

from django.db import migrations

def add_digests(apps, schema_editor):
    Photo = apps.get_model('photos', 'Photo')
    for photo in Photo.objects.all():
        hash_sha1 = hashlib.sha1()
        for chunk in iter(lambda: photo.file.read(4096), b""):
            hash_sha1.update(chunk)
        photo._digest = hash_sha1.hexdigest()
        photo.save()

class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_photo__digest'),
    ]

    operations = [
        migrations.RunPython(add_digests),
    ]
