# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_generate_digests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Photo',
            name='_digest',
            field=models.CharField(
                max_length=40,
                verbose_name='digest')),
    ]
