# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20170503_2101'),
        ('photos', '0009_auto_20170503_2001'),
    ]

    operations = [
    ]
