# Generated by Django 3.1.3 on 2021-01-25 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_auto_20200907_1835'),
        ('photos', '0012_remove_album_title_nl'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event'),
        ),
    ]
