# Generated by Django 4.0.4 on 2022-05-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0040_remove_profile_auto_renew'),
        ('photos', '0014_auto_20210315_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudos', to='photos.photo')),
            ],
        ),
    ]
