# Generated by Django 3.1.4 on 2021-03-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_auto_20210315_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-date', 'title')},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='title_en',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(blank=True, help_text='Leave empty to take over the title of the event', max_length=200, verbose_name='title'),
        ),
    ]
