# Generated by Django 4.0.7 on 2022-09-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0041_alter_profile_photo'),
        ('photos', '0016_like_delete_kudo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('photo', 'member')},
        ),
    ]
