# Generated by Django 4.1.2 on 2022-11-02 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0041_alter_profile_photo"),
        ("photos", "0017_alter_like_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="members.member",
                verbose_name="Member",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="photo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="photos.photo",
                verbose_name="Photo",
            ),
        ),
    ]
