# Generated by Django 4.1.6 on 2023-02-08 19:37

from django.db import migrations
import photos.models
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0018_alter_like_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=thumbnails.fields.ImageField(
                upload_to=photos.models.photo_uploadto, verbose_name="file"
            ),
        ),
    ]
