# Generated by Django 4.1.4 on 2023-02-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0018_alter_like_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="new_album_notification",
        ),
    ]
