# Generated by Django 4.1.7 on 2023-03-15 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0019_alter_photo_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="new_album_notification",
        ),
    ]
