# Generated by Django 4.1.7 on 2023-03-15 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0018_alter_like_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="new_album_notification",
        ),
    ]
