# Generated by Django 4.1.7 on 2023-03-22 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0020_remove_album_new_album_notification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={"ordering": ("pk",)},
        ),
    ]
