# Generated by Django 4.2.4 on 2023-09-13 16:28

from django.db import migrations


def delete_hidden(apps, schema_editor):
    Photo = apps.get_model("photos", "Photo")
    for hidden in Photo.objects.filter(hidden=True):
        hidden.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0022_alter_like_member"),
    ]

    operations = [
        migrations.RunPython(delete_hidden, migrations.RunPython.noop),
    ]
