# Generated by Django 4.2.4 on 2023-09-14 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0023_remove_photo_hidden"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="hidden",
        ),
    ]
