# Generated by Django 4.2.5 on 2023-09-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0024_remove_photo_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="_digest",
            field=models.CharField(
                blank=True, editable=False, max_length=40, verbose_name="digest"
            ),
        ),
    ]
