# Generated by Django 4.2.7 on 2023-12-06 18:38

from django.db import migrations


def check_unrotated(apps, schema_editor):
    Photo = apps.get_model("photos", "Photo")
    rotated = Photo.objects.exclude(rotation=0)
    if rotated.exists():
        raise Exception(
            "photos with rotation != 0 found, fix these before removing rotation field"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0025_alter_photo__digest"),
    ]

    operations = [
        migrations.RunPython(check_unrotated, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="photo",
            name="rotation",
        ),
    ]
