# Generated by Django 4.2.6 on 2023-12-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0026_remove_photo_rotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="is_processing",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="This album is hidden until fully uploaded",
                verbose_name="is processing",
            ),
        ),
    ]
